const RULES='https://www.lansstyrelsen.se/gotland/djur/fiske/recreational-fishing.html';
const HVMFS='https://www.havochvatten.se/download/18.66b74fcf189fa80353fab44/1708708185345/HVMFS%202023-11-ev.pdf';
const SOURCES={osm:'https://www.openstreetmap.org/copyright',emodnet:'https://emodnet.ec.europa.eu/en/bathymetry',openmeteo:'https://open-meteo.com/',copernicus:'https://data.marine.copernicus.eu/product/BALTICSEA_ANALYSISFORECAST_PHY_003_006/description',fiskeregler:'https://svenskafiskeregler.lansstyrelsen.se/'};
const FISH_GIS='https://ext-geodata-acc.lansstyrelsen.se/arcgis/rest/services/svenskafiskeregler/lst_svenskafiskeregler/MapServer/0/query';
const spots=[
['Lickershamn',57.8259,18.5161,5,280,'Kalk, Stein, Rinnen, Tang','Lickershamnsån'],['Sigsarve Strand',57.8664,18.5328,4,285,'Klint, Kies, Stein, Tang','Ihreån'],['Häftingsklint',57.8855,18.5487,4,285,'Klint, Stein, Kanten',''],['Hallshuk',57.9238,18.7442,5,310,'Kies, Tang, Kalkkante',''],['Kappelshamn West',57.8554,18.7468,4,275,'Bucht, Stein, Mischgrund','Vaste å / Kioskbäcken'],['Kappelshamn Ost / Bläse',57.8412,18.8330,4,55,'Kalk, Stein, flache Kanten',''],['Fårösund West',57.8629,19.0302,3,255,'Strömung, Stein/Sand',''],['Fårö West / Lauter',57.9680,19.0908,4,285,'Kalk, Raukar, Riffkanten',''],['Fårö Nord / Ekeviken',58.0087,19.2528,3,15,'Bucht, Sand/Stein',''],['Slite Außenküste',57.7061,18.8485,3,70,'Inseln, Stein, Rinnen',''],['Åminne / Gothem',57.5729,18.8098,3,85,'Sand, Stein, Flachwasser','Vikeån / Gothemsån'],['Katthammarsvik',57.4321,18.8626,4,95,'Stein, Buchten, Kanten',''],['Herrvik / Östergarn',57.4200,18.9330,5,100,'Riffe, Tangbänder, Rinnen',''],['Sandviken / Östergarn',57.4038,18.9204,4,105,'Sand-Riff-Mischgrund',''],['Ljugarn / Folhammar',57.3319,18.7270,5,105,'Kalkriff, Raukar, Tang','Halsegårdaån / Hugreifsån / Gartarveån / Bane å'],['Närsholmen',57.2202,18.7110,4,120,'Flache Landzunge, Rinnen','Närkån'],['Grötlingbo',57.1008,18.4045,3,155,'Flache Kalk-/Steinküste',''],['Holmhällar',56.9800,18.2904,4,145,'Raukar, Stein, Buchten',''],['Hoburgen',56.9185,18.1170,4,205,'Klippen, Kalkkanten',''],['Burgsvik West',57.0288,18.0842,3,265,'Bucht, Sand/Stein',''],
// v6.1: Djupvik auf den tatsächlich kartierten Küsten-/Hafenbereich korrigiert
['Djupvik / Ekstakusten',57.3084,18.1490,4,270,'Offene Stein-/Riffküste, Sandstrand',''],['Klintehamn Süd',57.3618,18.1150,3,270,'Riffstruktur, Mischgrund',''],['Västergarn',57.4381,18.0940,3,275,'Bucht, Sand/Stein','Västergarnsån'],['Gnisvärd / Tofta',57.5045,18.0730,4,280,'Flach, Sand/Stein',''],
// v6.1: Själsö auf Själsö hamn / reale Westküste korrigiert
['Själsö',57.6922,18.3521,3,285,'Kalk, Stein, Kanten','Själsöån / Kolenskvarnån']
].map((x,i)=>({id:i+1,name:x[0],lat:x[1],lon:x[2],rating:x[3],facing:x[4],structure:x[5],protected:x[6]}));

const map=L.map('map',{zoomControl:true}).setView([57.47,18.55],9);
L.control.scale({position:'bottomright',imperial:false,maxWidth:120}).addTo(map);
const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri'});
const bathy=L.tileLayer.wms('https://ows.emodnet-bathymetry.eu/wms',{layers:'emodnet:mean_multicolour',format:'image/png',transparent:true,opacity:.62,attribution:'EMODnet Bathymetry'});
const spotLayer=L.layerGroup().addTo(map),parkingLayer=L.layerGroup(),customLayer=L.layerGroup().addTo(map),homeLayer=L.layerGroup().addTo(map),windLayer=L.layerGroup(),currentLayer=L.layerGroup(),tempLayer=L.layerGroup(),protectedLayer=L.layerGroup().addTo(map),shore50Layer=L.layerGroup();
let satelliteOn=false,addMode=false,homeMode=false,selectedSpot=null,watchId=null,lastProtectionNotice=0,timelineIndex=0,timelineHours=[],spotListMode='all',officialProtectionFeatures=[],coastSnapRunning=false,active={wind:false,current:false,temp:false,bathy:false,parking:false,spots:true,custom:true,home:true,protected:true};
let customSpots=JSON.parse(localStorage.getItem('gst-custom-v6')||'[]');let home=JSON.parse(localStorage.getItem('gst-home-v6')||'null');
const favs=new Set(JSON.parse(localStorage.getItem('gst-favs')||'[]'));
const $=s=>document.querySelector(s);const status=t=>$('#status').textContent=t;
function compass(d){if(d==null)return'–';return ['N','NO','O','SO','S','SW','W','NW'][Math.round(d/45)%8]}
function angleDiff(a,b){let d=Math.abs(a-b)%360;return Math.min(d,360-d)}
function exposure(s,d){if(d==null)return'–';const x=angleDiff(s.facing,d);return x<=35?'auflandig':x<=80?'schräg auflandig':x<=120?'seitlich':'ablandig'}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function openSheet(html){cancelModes(false);$('#sheetBody').innerHTML=html;$('#sheet').classList.remove('hidden')}
function closeSheet(){$('#sheet').classList.add('hidden');$('#sheetBody').innerHTML=''}
$('#closeSheet').onclick=closeSheet;$('#sheet').onclick=e=>{if(e.target.id==='sheet')closeSheet()};
function googleNav(lat,lon){window.open(`https://www.google.com/maps/dir/?api=1&destination=${lat},${lon}`,'_blank')}
function score(w,m,s){let n=35+s.rating*6;if(w?.wind_speed_10m>=8&&w.wind_speed_10m<=28)n+=12;if(w?.wind_direction_10m!=null){let d=angleDiff(s.facing,w.wind_direction_10m);if(d<70)n+=12;if(d>145)n-=10}if(m?.wave_height>=.2&&m.wave_height<=1)n+=12;if(m?.sea_surface_temperature>=4&&m.sea_surface_temperature<=14)n+=10;return Math.max(0,Math.min(100,Math.round(n)))}
async function live(s,forecast=false){let h=forecast?'&hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m&forecast_hours=48':'';let mh=forecast?'&hourly=wave_height,wave_direction,sea_surface_temperature,ocean_current_velocity,ocean_current_direction&forecast_hours=48':'';let wu=`https://api.open-meteo.com/v1/forecast?latitude=${s.lat}&longitude=${s.lon}&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m&wind_speed_unit=kmh&timezone=auto${h}`;let mu=`https://marine-api.open-meteo.com/v1/marine?latitude=${s.lat}&longitude=${s.lon}&current=wave_height,wave_direction,sea_surface_temperature,ocean_current_velocity,ocean_current_direction&velocity_unit=kn&timezone=auto&cell_selection=sea${mh}`;let [w,m]=await Promise.allSettled([json(wu),json(mu)]);return{w:w.value||null,m:m.value||null}}
function seasonActive(){let m=new Date().getMonth()+1;return m>=9||m===1}
function destination(lat,lon,bearing,meters){let R=6371000,b=bearing*Math.PI/180,p1=lat*Math.PI/180,l1=lon*Math.PI/180,d=meters/R;let p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(b));let l2=l1+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return[p2*180/Math.PI,l2*180/Math.PI]}
function bearing(a,b){let p1=a[0]*Math.PI/180,p2=b[0]*Math.PI/180,dl=(b[1]-a[1])*Math.PI/180;let y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function seaBearing(s){let c=s.lat>57.84&&s.lon>18.95?[57.94,19.18]:[57.48,18.48];return bearing(c,[s.lat,s.lon])}
function satCenters(s){let b=seaBearing(s);return [destination(s.lat,s.lon,b,320),destination(s.lat,s.lon,b,145),destination(s.lat,s.lon,b,65)];}
function spotIcon(s){return L.divIcon({className:'numberedSpot',html:`<span>${s.id}</span>`,iconSize:[30,30],iconAnchor:[15,15]})}
function customIcon(i){return L.divIcon({className:'customSpotIcon',html:`<span>E${i+1}</span>`,iconSize:[34,34],iconAnchor:[17,17]})}

async function openSpot(s,isCustom=false){selectedSpot=s;map.setView([s.lat,s.lon],14);let title=isCustom?`E${customSpots.indexOf(s)+1} · ${s.name}`:`${s.id} · ${s.name}`;openSheet(`<h2>${favs.has(s.id)?'★ ':''}${title}</h2><div class="subtle">${isCustom?(s.note||'Eigener Spot'):`${'★'.repeat(s.rating)} · ${s.structure} · Küste ${compass(s.facing)}`}</div><div id="spotLive" class="metricGrid"><div class="metric"><small>Live-Daten</small><b>lädt…</b></div></div><div class="actions">${!isCustom?`<button id="favA" class="actionBtn">${favs.has(s.id)?'★ Favorit':'☆ Favorit'}</button>`:''}<button id="parkA" class="actionBtn primary">🅿 Parkplatz</button><button id="navA" class="actionBtn">↗ Spot navigieren</button>${isCustom?'<button id="ce" class="actionBtn">✎ Bearbeiten</button><button id="cd" class="actionBtn danger">Löschen</button>':''}</div>${s.protected?`<div class="officialBox">⚠ ${seasonActive()?'Schutzzeit aktiv. ':''}Nähe eines geschützten Gewässers (${s.protected}). Maßgeblich ist die amtliche Schutzfläche. <a href="${RULES}" target="_blank">Offizielle Regeln</a></div>`:''}<h3>Satellitenansicht</h3><div class="subtle">Die Bildausschnitte sind bewusst seewärts versetzt, damit Küstenlinie und Flachwasser sichtbar bleiben.</div><div class="satGrid"><div><div id="sat1" class="satMap"></div><div class="satCap">Übersicht</div></div><div><div id="sat2" class="satMap"></div><div class="satCap">Küste</div></div><div><div id="sat3" class="satMap"></div><div class="satCap">Detail</div></div></div><div id="parkResults"></div>`);
 if(!isCustom)$('#favA').onclick=()=>{favs.has(s.id)?favs.delete(s.id):favs.add(s.id);localStorage.setItem('gst-favs',JSON.stringify([...favs]));openSpot(s);renderList()};$('#navA').onclick=()=>googleNav(s.lat,s.lon);$('#parkA').onclick=()=>loadParkingNear(s,true);
 if(isCustom){$('#ce').onclick=()=>editCustom(s);$('#cd').onclick=()=>{if(confirm('Spot löschen?')){customSpots=customSpots.filter(x=>x.id!==s.id);saveCustom();renderCustom();closeSheet()}}}
 let centers=satCenters(s);[13,15,17].forEach((z,i)=>setTimeout(()=>{let mm=L.map('sat'+(i+1),{zoomControl:false,attributionControl:false,scrollWheelZoom:false}).setView(centers[i],z);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19}).addTo(mm);L.circleMarker([s.lat,s.lon],{radius:4,weight:1,fillOpacity:.8}).addTo(mm)},50));
 try{let r=await live(s,true),w=r.w?.current,m=r.m?.current,sc=score(w,m,{rating:s.rating||3,facing:s.facing||270});$('#spotLive').innerHTML=`<div class="metric"><small>Score</small><b>${sc}/100</b></div><div class="metric"><small>Wind</small><b>${w?.wind_speed_10m??'–'} km/h</b><small>${compass(w?.wind_direction_10m)} · ${exposure({facing:s.facing||270},w?.wind_direction_10m)}</small></div><div class="metric"><small>Welle</small><b>${m?.wave_height??'–'} m</b><small>${compass(m?.wave_direction)}</small></div><div class="metric"><small>Wasser</small><b>${m?.sea_surface_temperature??'–'} °C</b><small>Strömung ${m?.ocean_current_velocity??'–'} kn ${compass(m?.ocean_current_direction)}</small></div>`}catch{$('#spotLive').innerHTML='<div class="warnBox">Live-Daten derzeit nicht verfügbar.</div>'}}

function renderSpots(){spotLayer.clearLayers();spots.forEach(s=>L.marker([s.lat,s.lon],{title:`${s.id} ${s.name}`,icon:spotIcon(s)}).on('click',()=>openSpot(s)).addTo(spotLayer))}renderSpots();
function renderList(){let b=$('#spotList');b.innerHTML=`<div class="spotFilter"><button data-mode="all" class="${spotListMode==='all'?'active':''}">Alle</button><button data-mode="built" class="${spotListMode==='built'?'active':''}">Spots</button><button data-mode="own" class="${spotListMode==='own'?'active':''}">Eigene</button></div>`;let addBuilt=spotListMode!=='own',addOwn=spotListMode!=='built';if(addBuilt)spots.forEach(s=>{let d=document.createElement('div');d.className='spotCard';d.innerHTML=`<h3><span class="listNo">${s.id}</span>${favs.has(s.id)?'★ ':''}${s.name}</h3><p>${s.structure}</p><span class="badge">Küste ${compass(s.facing)}</span>`;d.onclick=()=>openSpot(s);b.appendChild(d)});if(addOwn)customSpots.forEach((s,i)=>{let d=document.createElement('div');d.className='spotCard ownCard';d.innerHTML=`<h3><span class="listNo ownNo">E${i+1}</span>${s.name}</h3><p>${s.note||'Eigener Spot'}</p><span class="badge">Eigener Spot</span>`;d.onclick=()=>openSpot(s,true);b.appendChild(d)});b.querySelectorAll('.spotFilter button').forEach(x=>x.onclick=()=>{spotListMode=x.dataset.mode;renderList();applySpotVisibility()})}
function applySpotVisibility(){let showBuilt=spotListMode!=='own',showOwn=spotListMode!=='built';if(showBuilt&&active.spots)spotLayer.addTo(map);else if(map.hasLayer(spotLayer))map.removeLayer(spotLayer);if(showOwn&&active.custom)customLayer.addTo(map);else if(map.hasLayer(customLayer))map.removeLayer(customLayer)}renderList();
function renderCustom(){customLayer.clearLayers();customSpots.forEach((s,i)=>L.marker([s.lat,s.lon],{title:s.name,icon:customIcon(i)}).bindTooltip(`E${i+1} · ${s.name}`).on('click',()=>openSpot(s,true)).addTo(customLayer));renderList()}renderCustom();
function saveCustom(){localStorage.setItem('gst-custom-v6',JSON.stringify(customSpots))}
function editCustom(s){openSheet(`<h2>Eigenen Spot</h2><form id="cf" class="formGrid"><label class="span2">Name<input name="name" required value="${s?.name||''}"></label><label class="span2">Notiz<textarea name="note">${s?.note||''}</textarea></label><label>Bewertung<select name="rating"><option>1</option><option>2</option><option selected>3</option><option>4</option><option>5</option></select></label><label>Küste zeigt nach<select name="facing"><option value="0">N</option><option value="90">O</option><option value="180">S</option><option value="270" selected>W</option></select></label><button class="actionBtn primary span2">Speichern & Detail öffnen</button></form>`);$('#cf').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);s.name=f.get('name');s.note=f.get('note');s.rating=+f.get('rating');s.facing=+f.get('facing');saveCustom();renderCustom();openSpot(s,true)}}
function cancelModes(msg=true){addMode=false;homeMode=false;$('#addSpotBtn')?.classList.remove('active');$('#homeBtn')?.classList.remove('active');if($('#addSpotBtn'))$('#addSpotBtn').textContent='＋ Spot';if($('#homeBtn'))$('#homeBtn').textContent='⌂ Ferienhaus';if(msg)status('Auswahl abgebrochen.')}
map.on('click',e=>{if(addMode){cancelModes(false);let s={id:'c'+Date.now(),lat:e.latlng.lat,lon:e.latlng.lng,name:'Neuer Spot',note:'',rating:3,facing:Math.round(seaBearing({lat:e.latlng.lat,lon:e.latlng.lng})/45)*45%360};customSpots.push(s);saveCustom();renderCustom();editCustom(s)}else if(homeMode){cancelModes(false);home={lat:e.latlng.lat,lon:e.latlng.lng,name:'Ferienhaus'};localStorage.setItem('gst-home-v6',JSON.stringify(home));renderHome();status('Ferienhaus gespeichert.')}});
function renderHome(){homeLayer.clearLayers();if(home)L.marker([home.lat,home.lon],{icon:L.divIcon({className:'homeIcon',html:'🏠',iconSize:[28,28]})}).bindTooltip(home.name).on('click',()=>googleNav(home.lat,home.lon)).addTo(homeLayer)}renderHome();

function hav(a,b){const R=6371000,p1=a[0]*Math.PI/180,p2=b[0]*Math.PI/180,dp=(b[0]-a[0])*Math.PI/180,dl=(b[1]-a[1])*Math.PI/180;const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function coastDistance(p,coastPts){let min=Infinity;for(const q of coastPts){let d=hav([p.lat,p.lon],q);if(d<min)min=d}return min}
async function parkingQuery(bounds){let bb=`${bounds.s},${bounds.w},${bounds.n},${bounds.e}`;let q=`[out:json][timeout:25];(node[amenity=parking](${bb});way[amenity=parking](${bb});way[natural=coastline](${bb}););out center geom 250;`;return json('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q))}
function parseParking(d){let coast=[];d.elements.filter(x=>x.tags?.natural==='coastline').forEach(w=>(w.geometry||[]).forEach(g=>coast.push([g.lat,g.lon])));return d.elements.filter(x=>x.tags?.amenity==='parking').map(x=>({lat:x.lat||x.center?.lat,lon:x.lon||x.center?.lon,name:x.tags?.name||'Parkplatz',access:x.tags?.access||''})).filter(x=>x.lat&&(!x.access||!['private','no'].includes(x.access))).map(p=>({...p,coast:coastDistance(p,coast)})).filter(p=>p.coast<=330).sort((a,b)=>a.coast-b.coast)}
async function loadParkingNear(s,showInSheet=false){status('Suche küstennahe Parkplätze…');let dlat=.04,dlon=.075;try{let d=await parkingQuery({s:s.lat-dlat,w:s.lon-dlon,n:s.lat+dlat,e:s.lon+dlon}),arr=parseParking(d).filter(p=>hav([s.lat,s.lon],[p.lat,p.lon])<4000);parkingLayer.clearLayers();arr.forEach(p=>L.marker([p.lat,p.lon],{icon:L.divIcon({className:'parkingIcon',html:'P',iconSize:[25,25]})}).bindTooltip(`${p.name} · ~${Math.round(p.coast)} m zur Küste`).on('click',()=>googleNav(p.lat,p.lon)).addTo(parkingLayer));parkingLayer.addTo(map);active.parking=true;if(showInSheet){let box=$('#parkResults');box.innerHTML='<h3>Parkplätze ≤ ca. 300 m zur Küste</h3>'+(!arr.length?'<p class="subtle">Keine passenden OSM-Parkplätze gefunden.</p>':arr.slice(0,8).map((p,i)=>`<button class="actionBtn parkLink" data-i="${i}">🅿 ${p.name} · ~${Math.round(p.coast)} m</button>`).join(''));box.querySelectorAll('.parkLink').forEach(b=>b.onclick=()=>googleNav(arr[+b.dataset.i].lat,arr[+b.dataset.i].lon))}status(`${arr.length} küstennahe Parkplätze gefunden.`)}catch{status('Parkplatzsuche derzeit nicht verfügbar.')}}
async function loadParkingViewport(){if(map.getZoom()<11){status('Für Parkplätze bitte näher an die Küste zoomen.');return}let b=map.getBounds();try{let d=await parkingQuery({s:b.getSouth(),w:b.getWest(),n:b.getNorth(),e:b.getEast()}),arr=parseParking(d);parkingLayer.clearLayers();arr.forEach(p=>L.marker([p.lat,p.lon],{icon:L.divIcon({className:'parkingIcon',html:'P',iconSize:[25,25]})}).bindTooltip(`${p.name} · ~${Math.round(p.coast)} m zur Küste`).on('click',()=>googleNav(p.lat,p.lon)).addTo(parkingLayer));parkingLayer.addTo(map);active.parking=true;status(`${arr.length} Parkplätze ≤ ca. 300 m zur Küste.`)}catch{status('Parkplätze derzeit nicht verfügbar.')}}

// Küstenprüfung: vorhandene Spotnamen bleiben erhalten, die Marker werden bei Onlinebetrieb an die nächstgelegene OSM-Meeresküstenlinie gesetzt.
function nearestOnSegment(p,a,b){let x=p.lon,y=p.lat,x1=a.lon,y1=a.lat,x2=b.lon,y2=b.lat,dx=x2-x1,dy=y2-y1,t=((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy||1);t=Math.max(0,Math.min(1,t));return{lat:y1+t*dy,lon:x1+t*dx}}
async function snapOneSpot(s){let cache=JSON.parse(localStorage.getItem('gst-coastsnap-v611')||'{}');if(cache[s.id]){s.lat=cache[s.id][0];s.lon=cache[s.id][1];return true}for(let radius of [.035,.07,.13]){let bb=`${s.lat-radius},${s.lon-radius},${s.lat+radius},${s.lon+radius}`,q=`[out:json][timeout:20];way[natural=coastline](${bb});out geom;`;try{let d=await json('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q)),best=null,bd=Infinity;for(let w of d.elements||[]){let g=w.geometry||[];for(let i=1;i<g.length;i++){let n=nearestOnSegment({lat:s.lat,lon:s.lon},g[i-1],g[i]),dist=hav([s.lat,s.lon],[n.lat,n.lon]);if(dist<bd){bd=dist;best=n}}}if(best){s.lat=best.lat;s.lon=best.lon;cache[s.id]=[+best.lat.toFixed(6),+best.lon.toFixed(6)];localStorage.setItem('gst-coastsnap-v611',JSON.stringify(cache));return true}}catch{}}return false}
async function snapAllSpots(){if(coastSnapRunning)return;coastSnapRunning=true;status('Prüfe Spotpositionen gegen die OSM-Meeresküste…');let ok=0;for(let s of spots){if(await snapOneSpot(s))ok++;renderSpots();renderList()}coastSnapRunning=false;status(`${ok}/${spots.length} Spotpositionen an der Meeresküste geprüft.`)}
setTimeout(snapAllSpots,500);

// Grobe reine Darstellungs-Landmaske. Sie ist KEINE Rechts-/Küstengrenze und dient nur dazu, Wetter-/Meeres-Pfeile auf Land zu unterdrücken.
const gotlandPoly=[[56.90,18.05],[56.98,18.01],[57.08,18.02],[57.18,18.05],[57.30,18.06],[57.42,18.04],[57.52,18.08],[57.62,18.16],[57.72,18.25],[57.82,18.35],[57.90,18.46],[57.96,18.58],[57.98,18.72],[57.94,18.86],[57.86,18.91],[57.76,18.93],[57.66,18.96],[57.56,18.99],[57.46,18.98],[57.36,18.88],[57.26,18.75],[57.16,18.61],[57.08,18.50],[57.00,18.40],[56.94,18.28]];
const faroPoly=[[57.85,18.98],[57.88,19.04],[57.92,19.02],[57.98,19.04],[58.04,19.11],[58.07,19.24],[58.03,19.38],[57.96,19.39],[57.90,19.31],[57.86,19.18]];
function inPoly(lat,lon,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let yi=poly[i][0],xi=poly[i][1],yj=poly[j][0],xj=poly[j][1];let hit=((yi>lat)!=(yj>lat))&&(lon<(xj-xi)*(lat-yi)/(yj-yi)+xi);if(hit)inside=!inside}return inside}
function isLand(p){return inPoly(p.lat,p.lon,gotlandPoly)||inPoly(p.lat,p.lon,faroPoly)}
const vectorPoints=[];for(let lat=56.90;lat<=58.06;lat+=.055)for(let lon=17.98;lon<=19.40;lon+=.065){let p={lat:+lat.toFixed(3),lon:+lon.toFixed(3)};if(!isLand(p))vectorPoints.push(p)}
function currentColor(v){if(v<.10)return'#f4fbf3';if(v<.25)return'#d9efd5';if(v<.50)return'#bfe2b8';if(v<.85)return'#91cf86';if(v<1.20)return'#63bb67';if(v<1.60)return'#fff04a';if(v<2.10)return'#ffb23d';if(v<2.50)return'#f36b2d';return'#d9362b'}
function currentClass(v){if(v<.08)return'nahezu still';if(v<.25)return'sehr schwach';if(v<.50)return'schwach';if(v<.85)return'mäßig';if(v<1.20)return'deutlich';if(v<1.60)return'kräftig';if(v<2.10)return'stark';return'sehr stark'}
function currentGlyphIcon(dir,v){
  if(v<.08)return L.divIcon({className:'currentGlyph',html:`<span class="currentDot"></span>`,iconSize:[12,12],iconAnchor:[6,6]});
  let len=Math.max(12,Math.min(38,11+v*12)),thick=Math.max(1.5,Math.min(4.8,1.25+v*1.45)),head=Math.max(4.8,Math.min(9,4.5+v*1.7));
  return L.divIcon({className:'currentGlyph',html:`<span class="currentArrowWrap" style="width:${len}px;height:${Math.max(15,head*2)}px;transform:rotate(${dir-90}deg)"><span class="currentShaft" style="width:${Math.max(4,len-head)}px;height:${thick}px"></span><span class="currentHead" style="border-left-width:${head}px;border-top-width:${head*.62}px;border-bottom-width:${head*.62}px"></span></span>`,iconSize:[len+8,Math.max(18,head*2+4)],iconAnchor:[(len+8)/2,Math.max(18,head*2+4)/2]});
}
let currentCache=new Map();
function uvFrom(v,dir){let r=dir*Math.PI/180;return{u:v*Math.sin(r),n:v*Math.cos(r)}}
function vdFrom(u,n){let v=Math.hypot(u,n),dir=(Math.atan2(u,n)*180/Math.PI+360)%360;return{v,dir}}
function idwCurrent(lat,lon,samples){let near=samples.map(a=>{let dx=(lon-a.lon)*Math.cos(lat*Math.PI/180),dy=lat-a.lat;return{a,d2:dx*dx+dy*dy}}).sort((x,y)=>x.d2-y.d2).slice(0,8),su=0,sn=0,sw=0;for(const x of near){let a=x.a,d2=x.d2;if(d2<1e-8)return{v:a.v,dir:a.dir};let w=1/Math.pow(d2,1.15);su+=a.u*w;sn+=a.n*w;sw+=w}return sw?vdFrom(su/sw,sn/sw):null}
function currentSourcePoints(){let out=[];for(let lat=56.88;lat<=58.10;lat+=.14)for(let lon=17.94;lon<=19.45;lon+=.17){let p={lat:+lat.toFixed(4),lon:+lon.toFixed(4)};if(!isLand(p))out.push(p)}return out}
async function fetchCurrentSamples(){let key=timelineIndex;if(currentCache.has(key))return currentCache.get(key);let pts=currentSourcePoints(),lats=pts.map(p=>p.lat).join(','),lons=pts.map(p=>p.lon).join(',');let url=`https://marine-api.open-meteo.com/v1/marine?latitude=${lats}&longitude=${lons}&hourly=ocean_current_velocity,ocean_current_direction&velocity_unit=kn&forecast_hours=48&timezone=auto&cell_selection=sea`;let data=await json(url),arr=Array.isArray(data)?data:[data],samples=[];arr.forEach((d,i)=>{let idx=Math.min(timelineIndex,(d.hourly?.time?.length||1)-1),v=d.hourly?.ocean_current_velocity?.[idx],dir=d.hourly?.ocean_current_direction?.[idx];if(v!=null&&dir!=null){let uv=uvFrom(+v,+dir);samples.push({...pts[i],v:+v,dir:+dir,...uv})}});currentCache.set(key,samples);return samples}
function denseCurrentPoints(){let b=map.getBounds(),z=map.getZoom(),latStep=z>=13?.014:z>=12?.018:z>=11?.024:z>=10?.034:.050,lonStep=latStep*1.55;let s=Math.max(56.86,b.getSouth()),n=Math.min(58.12,b.getNorth()),w=Math.max(17.90,b.getWest()),e=Math.min(19.50,b.getEast()),out=[];for(let lat=s;lat<=n;lat+=latStep)for(let lon=w;lon<=e;lon+=lonStep){let p={lat:+lat.toFixed(5),lon:+lon.toFixed(5)};if(!isLand(p))out.push(p)}return out.slice(0,650)}
function drawCurrentBands(samples,layer){
  let b=map.getBounds(),s=Math.max(56.84,b.getSouth()),n=Math.min(58.14,b.getNorth()),w=Math.max(17.86,b.getWest()),e=Math.min(19.54,b.getEast());
  if(s>=n||w>=e)return;
  let px=Math.max(220,Math.min(520,Math.round(map.getSize().x*.62))),ratio=Math.max(.45,Math.min(1.8,map.getSize().y/map.getSize().x)),py=Math.max(180,Math.round(px*ratio));
  let c=document.createElement('canvas');c.width=px;c.height=py;let ctx=c.getContext('2d',{alpha:true}),step=3;ctx.imageSmoothingEnabled=false;
  for(let y=0;y<py;y+=step){let lat=n-(y/py)*(n-s);for(let x=0;x<px;x+=step){let lon=w+(x/px)*(e-w),p={lat,lon};if(isLand(p))continue;let q=idwCurrent(lat,lon,samples);if(!q)continue;ctx.fillStyle=currentColor(q.v);ctx.fillRect(x,y,step+1,step+1)}}
  L.imageOverlay(c.toDataURL('image/png'),[[s,w],[n,e]],{opacity:.78,interactive:false,className:'currentBands'}).addTo(layer);
}
function drawDenseCurrent(samples,layer){
  drawCurrentBands(samples,layer);
  for(const p of denseCurrentPoints()){let x=idwCurrent(p.lat,p.lon,samples);if(!x)continue;L.marker([p.lat,p.lon],{icon:currentGlyphIcon(x.dir,x.v),keyboard:false,interactive:false}).addTo(layer)}
}
let copernicusCfg=null;
async function getCopernicusCfg(){if(copernicusCfg===false)return null;if(copernicusCfg)return copernicusCfg;try{let r=await fetch('https://wmts.marine.copernicus.eu/teroWmts?service=WMTS&version=1.0.0&request=GetCapabilities');if(!r.ok)throw Error('WMTS '+r.status);let doc=new DOMParser().parseFromString(await r.text(),'application/xml'),layers=[...doc.getElementsByTagNameNS('*','Layer')],chosen=null;for(let l of layers){let ids=[...l.getElementsByTagNameNS('*','Identifier')];let id=ids[0]?.textContent||'';if(id.includes('BALTICSEA_ANALYSISFORECAST_PHY_003_006')&&id.toLowerCase().includes('pt15m-i')&&id.includes('sea_water_velocity')){chosen=l;break}}if(!chosen){for(let l of layers){let id=[...l.getElementsByTagNameNS('*','Identifier')][0]?.textContent||'';if(id.includes('BALTICSEA_ANALYSISFORECAST_PHY_003_006')&&id.includes('sea_water_velocity')){chosen=l;break}}}if(!chosen)throw Error('Baltic current WMTS layer not found');let layerId=[...chosen.getElementsByTagNameNS('*','Identifier')][0].textContent,styles=[...chosen.getElementsByTagNameNS('*','Style')],style='';for(let st of styles){let title=[...st.getElementsByTagNameNS('*','Title')].map(x=>x.textContent).join(' '),id=[...st.getElementsByTagNameNS('*','Identifier')][0]?.textContent||'';if((title+' '+id).toLowerCase().includes('vector')&&(title+' '+id).toLowerCase().includes('solid')){style=id;break}}if(!style)for(let st of styles){let title=[...st.getElementsByTagNameNS('*','Title')].map(x=>x.textContent).join(' '),id=[...st.getElementsByTagNameNS('*','Identifier')][0]?.textContent||'';if((title+' '+id).toLowerCase().includes('vector')){style=id;break}}if(!style)style=[...styles[0]?.getElementsByTagNameNS('*','Identifier')||[]][0]?.textContent||'';copernicusCfg={layerId,style};return copernicusCfg}catch(e){console.warn('Copernicus WMTS unavailable',e);copernicusCfg=false;return null}}
async function addCopernicusCurrent(layer){let cfg=await getCopernicusCfg();if(!cfg)return false;let time=(timelineHours[timelineIndex]||new Date()).toISOString(),url='https://wmts.marine.copernicus.eu/teroWmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&FORMAT=image%2Fpng&LAYER='+encodeURIComponent(cfg.layerId)+'&tilematrixset=EPSG:3857@2x&tilematrix={z}&tilecol={x}&tilerow={y}&time='+encodeURIComponent(time)+(cfg.style?'&STYLE='+encodeURIComponent(cfg.style):'');L.tileLayer(url,{opacity:.18,maxZoom:10,attribution:'© EU Copernicus Marine Service · SMHI'}).addTo(layer);return true}
function arrowIcon(kind,dir,val,label){let size=Math.max(16,Math.min(34,16+val*.35));return L.divIcon({className:'vectorIcon',html:`<div class="vectorArrow ${kind}" style="font-size:${size}px;color:#183f82;transform:rotate(${dir-90}deg)">➤</div><div class="vectorValue">${label}</div>`,iconSize:[48,48],iconAnchor:[24,24]})}
function timeParam(){return timelineHours[timelineIndex]||null}
async function loadVectors(kind){let layer=kind==='wind'?windLayer:currentLayer;layer.clearLayers();active[kind]=true;updateTimeline();if(kind==='current'){status('Lade dichtes Strömungsfeld…');let cop=false;try{cop=await addCopernicusCurrent(layer)}catch{}try{let samples=await fetchCurrentSamples();drawDenseCurrent(samples,layer);layer.addTo(map);status(cop?'Strömung aktiv: klassierte Farbbänder + dichte Richtungspfeile; Copernicus dezent im Hintergrund.':'Strömung aktiv: klassierte Farbbänder + dichte Richtungspfeile.')}catch(e){console.warn(e);layer.addTo(map);status(cop?'Copernicus-Strömungsfeld aktiv; Pfeildaten derzeit nicht erreichbar.':'Strömungsdaten derzeit nicht verfügbar.')}return}status('Lade Windfeld…');let pts=vectorPoints.filter((_,i)=>i%2===0);await Promise.allSettled(pts.map(async p=>{try{let d=await json(`https://api.open-meteo.com/v1/forecast?latitude=${p.lat}&longitude=${p.lon}&hourly=wind_speed_10m,wind_direction_10m&wind_speed_unit=kmh&forecast_hours=48&timezone=auto`),idx=Math.min(timelineIndex,(d.hourly?.time?.length||1)-1),v=d.hourly?.wind_speed_10m?.[idx],dir=d.hourly?.wind_direction_10m?.[idx];if(v!=null)L.marker([p.lat,p.lon],{icon:arrowIcon('wind',(dir+180)%360,v,Math.round(v))}).addTo(layer)}catch{}}));layer.addTo(map);status('Windfeld aktiv.')} 
function tempColor(t){if(t<6)return'#275aa8';if(t<9)return'#2c7bb6';if(t<12)return'#73add1';if(t<15)return'#abd9e9';if(t<17)return'#fdae61';if(t<19)return'#f46d43';return'#d73027'}
async function loadTemp(){tempLayer.clearLayers();active.temp=true;updateTimeline();status('Lade Wassertemperatur…');let pts=vectorPoints.filter((_,i)=>i%4===0);await Promise.allSettled(pts.map(async p=>{try{let d=await json(`https://marine-api.open-meteo.com/v1/marine?latitude=${p.lat}&longitude=${p.lon}&hourly=sea_surface_temperature&forecast_hours=48&timezone=auto&cell_selection=sea`),idx=Math.min(timelineIndex,(d.hourly?.time?.length||1)-1),t=d.hourly?.sea_surface_temperature?.[idx];if(t!=null)L.circle([p.lat,p.lon],{radius:7000,stroke:false,fillColor:tempColor(t),fillOpacity:.32}).bindTooltip(`${t} °C`).addTo(tempLayer)}catch{}}));tempLayer.addTo(map);status('Wassertemperatur aktiv.')} 
let shore50Loaded=false;
function offsetCoastWay(geom){let center=[57.47,18.55],out=[];for(let i=0;i<geom.length;i++){let p=geom[i],a=geom[Math.max(0,i-1)],b=geom[Math.min(geom.length-1,i+1)],tan=bearing([a.lat,a.lon],[b.lat,b.lon]),c1=destination(p.lat,p.lon,tan+90,50),c2=destination(p.lat,p.lon,tan-90,50),d1=hav(center,c1),d2=hav(center,c2);out.push(d1>d2?c1:c2)}return out}
async function loadShore50(){if(shore50Loaded){if(active.bathy&&!map.hasLayer(shore50Layer))shore50Layer.addTo(map);return}shore50Layer.clearLayers();status('Lade ca. 50-m-Küstenlinie…');let q='[out:json][timeout:45];way[natural=coastline](56.84,17.88,58.13,19.52);out geom;';try{let d=await json('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q));for(const w of d.elements||[]){let g=w.geometry||[];if(g.length<2)continue;let line=offsetCoastWay(g);L.polyline(line,{color:'#ffffff',weight:5,opacity:.88,interactive:false}).addTo(shore50Layer);L.polyline(line,{color:'#173e50',weight:2,opacity:.95,dashArray:'8 5',interactive:false}).addTo(shore50Layer)}shore50Loaded=true;if(active.bathy)shore50Layer.addTo(map);status('Wassertiefe aktiv · ca. 50-m-Orientierungslinie eingeblendet.')}catch(e){console.warn(e);status('Wassertiefe aktiv · 50-m-Küstenlinie konnte nicht geladen werden.')}}
function setLayer(key,on){active[key]=on;let layer={spots:spotLayer,custom:customLayer,home:homeLayer,protected:protectedLayer,parking:parkingLayer,bathy,wind:windLayer,current:currentLayer,temp:tempLayer}[key];if(!on){if(map.hasLayer(layer))map.removeLayer(layer);if(key==='bathy'&&map.hasLayer(shore50Layer))map.removeLayer(shore50Layer)}else if(key==='wind')loadVectors('wind');else if(key==='current')loadVectors('current');else if(key==='temp')loadTemp();else if(key==='parking')loadParkingViewport();else{layer.addTo(map);if(key==='bathy')loadShore50()}if(key==='spots'||key==='custom')applySpotVisibility();renderLegends();updateTimeline()}
function switchHtml(key,label){return `<div class="layerRow ${active[key]?'on':''}"><span>${label}</span><label class="switch"><input type="checkbox" data-layer="${key}" ${active[key]?'checked':''}><span class="slider"></span></label></div>`}
function layerSheet(){openSheet(`<h2>Karten-Layer</h2><p class="subtle">In der Spotliste kannst du zwischen Alle / Spots / Eigene wählen. Voreinstellung: Alle.</p><div class="layerList">${switchHtml('spots','🎣 Angelspots')}${switchHtml('custom','📌 Eigene Spots')}${switchHtml('parking','🅿 Küstenparkplätze ≤ ~300 m')}${switchHtml('protected','⚠ Schutzgebiete')}${switchHtml('current','🌊 Strömung')}${switchHtml('wind','💨 Wind')}${switchHtml('temp','🌡 Wassertemperatur')}${switchHtml('bathy','〰 Wassertiefen')}${switchHtml('home','🏠 Ferienhaus')}</div><p class="depthNote">Zeitabhängige Layer nutzen gemeinsam die Zeitachse unten auf der Karte. Strömung: zusammenhängende Geschwindigkeitsklassen wie in der Referenzansicht, darüber dichte schwarze Richtungspfeile. Kleine Punkte markieren nahezu stehendes Wasser; Länge und Dicke der Pfeile zeigen die Stärke. Wassertiefe: zusätzliche ca. 50-m-Orientierungslinie entlang der Küste.</p>`);document.querySelectorAll('[data-layer]').forEach(x=>x.onchange=e=>{setLayer(e.target.dataset.layer,e.target.checked);e.target.closest('.layerRow').classList.toggle('on',e.target.checked)})}
function renderLegends(){let b=$('#mapLegends');let html='';if(active.current)html+=`<div class="mapLegend currentLegend"><b>Strömung · kn</b><div class="currentLegendRows"><div class="currentLegendRow"><span class="currentLegendDot"></span><span>0–0,08 · nahezu still</span></div><div class="currentLegendRow"><span class="currentLegendSwatch" style="background:#d9efd5"></span><span>0,08–0,25 · sehr schwach</span></div><div class="currentLegendRow"><span class="currentLegendSwatch" style="background:#bfe2b8"></span><span>0,25–0,50 · schwach</span></div><div class="currentLegendRow"><span class="currentLegendSwatch" style="background:#91cf86"></span><span>0,50–0,85 · mäßig</span></div><div class="currentLegendRow"><span class="currentLegendSwatch" style="background:#63bb67"></span><span>0,85–1,20 · deutlich</span></div><div class="currentLegendRow"><span class="currentLegendSwatch" style="background:#fff04a"></span><span>1,20–1,60 · kräftig</span></div><div class="currentLegendRow"><span class="currentLegendSwatch" style="background:#ffb23d"></span><span>1,60–2,10 · stark</span></div><div class="currentLegendRow"><span class="currentLegendSwatch" style="background:#f36b2d"></span><span>2,10–2,50 · sehr stark</span></div><div class="currentLegendRow"><span class="currentLegendSwatch" style="background:#d9362b"></span><span>&gt;2,50 · extrem</span></div></div><small>Richtung = Pfeil · Länge + Dicke = Stärke</small></div>`;if(active.temp)html+=`<div class="mapLegend"><b>Wasser · °C</b><div class="grad tempGrad"></div><div class="ticks"><span>6</span><span>9</span><span>12</span><span>15</span><span>17</span><span>19+</span></div></div>`;if(active.bathy)html+=`<div class="mapLegend"><b>Wassertiefe · m</b><div class="grad depthGrad"></div><div class="ticks"><span>0</span><span>2</span><span>5</span><span>10</span><span>20</span><span>50+</span></div><small>EMODnet-Farbskala angenähert · gestrichelt: ca. 50 m vor der Küste</small></div>`;b.innerHTML=html;syncQuickLayers()}

function syncQuickLayers(){document.querySelectorAll('#quickLayers [data-quick]').forEach(btn=>{let k=btn.dataset.quick,on=k==='base'?(!active.bathy&&!active.temp&&!active.current):!!active[k];btn.classList.toggle('active',on)})}
function setQuickLayer(key){cancelModes(false);if(key==='base'){['bathy','temp','current'].forEach(k=>{if(active[k])setLayer(k,false)})}else{['bathy','temp','current'].forEach(k=>{if(k!==key&&active[k])setLayer(k,false)});setLayer(key,!active[key])}syncQuickLayers()}
document.querySelectorAll('#quickLayers [data-quick]').forEach(btn=>btn.onclick=()=>setQuickLayer(btn.dataset.quick));
function initTimeline(){let now=new Date();now.setMinutes(0,0,0);timelineHours=Array.from({length:48},(_,i)=>new Date(now.getTime()+i*3600000));let range=$('#timeRange'),timeline=$('#timeline');range.max=47;range.value=0;range.oninput=e=>{timelineIndex=+e.target.value;refreshTimed()};$('#playTime').onclick=playTimeline;/* Keep slider gestures inside the timeline instead of passing them to Leaflet map dragging. */if(window.L?.DomEvent){L.DomEvent.disableClickPropagation(timeline);L.DomEvent.disableScrollPropagation(timeline)}['pointerdown','pointermove','pointerup','touchstart','touchmove','touchend','mousedown','mousemove','mouseup','click'].forEach(type=>range.addEventListener(type,e=>e.stopPropagation(),{passive:true}));updateTimeline()}
let playTimer=null;function playTimeline(){if(playTimer){clearInterval(playTimer);playTimer=null;$('#playTime').textContent='▶';return}$('#playTime').textContent='Ⅱ';playTimer=setInterval(()=>{timelineIndex=(timelineIndex+1)%48;$('#timeRange').value=timelineIndex;refreshTimed()},1200)}
let refreshTimer;function refreshTimed(){updateTimeline();clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{if(active.current)loadVectors('current');if(active.wind)loadVectors('wind');if(active.temp)loadTemp()},250)}
function updateTimeline(){let show=active.current||active.wind||active.temp;$('#timeline').classList.toggle('hidden',!show);let d=timelineHours[timelineIndex];if(d)$('#timeLabel').textContent=timelineIndex===0?'Jetzt':d.toLocaleString('de-DE',{weekday:'short',hour:'2-digit',minute:'2-digit'})}

// Schutzgebiete: offizielle Geometrien aus Svenska Fiskeregler (Länsstyrelserna/HaV).
// Die Kartenanzeige ist eine Orientierungshilfe; rechtlich maßgeblich bleibt die veröffentlichte Vorschrift.
const protectionNames=['Själsö','Kolenskvarn','Lummelunda','Lickershamn','Ihre','Vaste','Kiosk','Vitärt','Välles','Arån','Hylu','Hultungs','Bång','Vägume','Vike','Gothem','Storsund','Djupån','Nygårds','Histilles','Halsegårda','Hugreif','Gartarve','Bane','Svajde','Lavas','Tuten','Närk','Kvarne','Snoder','Varbos','Robbjän','Västergarn','Kopparvik'];
function norm(x){return String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function isSeaTroutProtection(props){let text=norm([props?.NAMN,props?.REF_HVMFS,props?.REF_BILAGA].join(' '));return text.includes('2023:11')||protectionNames.some(n=>text.includes(norm(n)))}
async function loadOfficialProtections(){protectedLayer.clearLayers();status('Lade amtliche Schutzgebiete…');let params=new URLSearchParams({where:'1=1',geometry:'17.75,56.80,19.55,58.12',geometryType:'esriGeometryEnvelope',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'NAMN,REF_HVMFS,REF_BILAGA,REF_PARAGR,REF_KAPITE,REF_ID',returnGeometry:'true',outSR:'4326',f:'geojson'});try{let data=await json(FISH_GIS+'?'+params),features=(data.features||[]).filter(f=>isSeaTroutProtection(f.properties));officialProtectionFeatures=features;L.geoJSON({type:'FeatureCollection',features},{style:{color:'#a51f2d',weight:2,fillColor:'#e05260',fillOpacity:.28,dashArray:'6 4'},onEachFeature:(f,l)=>{let n=f.properties?.NAMN||'Schutzgebiet';l.bindPopup(`<b>${n}</b><br>Schutzgebiet aus Svenska Fiskeregler.<br>Meerforellen-Mündungsbereiche auf Gotland: Angelverbot 1. Sep.–31. Jan.<br><small>Kartengeometrie dient der Orientierung; rechtlich maßgeblich ist die Vorschrift.</small><br><a href="${RULES}" target="_blank">Länsstyrelsen</a> · <a href="${HVMFS}" target="_blank">HVMFS 2023:11</a>`)}}).addTo(protectedLayer);if(active.protected&&!map.hasLayer(protectedLayer))protectedLayer.addTo(map);status(`${features.length} amtliche Schutzflächen geladen.`)}catch(e){status('Amtliche Schutzflächen konnten nicht geladen werden.');console.warn(e)}}
function featureContainsPoint(f,lat,lon){let g=f.geometry;if(!g)return false;let polys=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];return polys.some(poly=>poly.some((ring,i)=>i===0&&inPoly(lat,lon,ring.map(c=>[c[1],c[0]]))))}
function pointInProtection(lat,lon){return officialProtectionFeatures.some(f=>featureContainsPoint(f,lat,lon))}
loadOfficialProtections();

async function today(){cancelModes(false);let box=$('#ranking');box.classList.remove('hidden');box.innerHTML='<b>☀ Beste Spots jetzt</b><p>Lade Bedingungen…</p>';let out=[];for(let s of spots){try{let r=await live(s),sc=score(r.w?.current,r.m?.current,s);out.push({s,sc})}catch{}}out.sort((a,b)=>b.sc-a.sc);box.innerHTML='<b>☀ Beste Spots jetzt</b>'+out.slice(0,5).map((x,i)=>`<div class="rankRow" data-id="${x.s.id}"><b>${x.s.id}</b><span>${x.s.name}</span><b>${x.sc}/100</b></div>`).join('');box.querySelectorAll('.rankRow').forEach(r=>r.onclick=()=>openSpot(spots.find(s=>s.id==r.dataset.id)))}
function moreSheet(){openSheet(`<h2>Mehr</h2><div class="actions"><button id="rules" class="actionBtn">⚠ Regeln & Schonzeit</button><button id="parkall" class="actionBtn">🅿 Parkplätze</button><button id="backup" class="actionBtn">⇩ Backup</button><button id="gpswarn" class="actionBtn">📍 GPS-Warnung</button><button id="sources" class="actionBtn">ⓘ Quellen & Lizenzen</button></div><div class="officialBox"><b>Meerforellen-Schutzbereiche:</b> Laut Länsstyrelsen gibt es 25 Schutzbereiche an 34 Gewässern. In den Mündungsbereichen gilt 1. September–31. Januar Angelverbot. Die App verwendet keine geschätzten Kreise.</div><p class="subtle">Die Schutzflächen werden live aus dem offiziellen Kartendienst Svenska Fiskeregler geladen. Die Kartendarstellung dient der Orientierung; rechtlich maßgeblich bleibt die Vorschrift.</p>`);$('#rules').onclick=()=>window.open(RULES,'_blank');$('#parkall').onclick=()=>{loadParkingViewport();closeSheet()};$('#backup').onclick=backup;$('#gpswarn').onclick=enableWatch;$('#sources').onclick=sourcesSheet}
function sourcesSheet(){openSheet(`<h2>Quellen & Lizenzen</h2><div class="sourceList"><p><b>Basiskarte / Parkplätze</b><br>© OpenStreetMap contributors · ODbL<br><a href="${SOURCES.osm}" target="_blank">Lizenz & Attribution</a></p><p><b>Satellitenbilder</b><br>Esri World Imagery · Attribution wird direkt auf der Kartenebene angezeigt.</p><p><b>Bathymetrie</b><br>EMODnet Bathymetry<br><a href="${SOURCES.emodnet}" target="_blank">Quelle</a></p><p><b>Wind / Wellen / SST / interpolierte Strömungspfeile</b><br>Open-Meteo / Marine Weather API<br><a href="${SOURCES.openmeteo}" target="_blank">Quelle</a></p><p><b>Hochauflösendes Strömungsfeld</b><br>Copernicus Marine / Baltic Sea Physics (SMHI), ca. 2 km Modellraster / 15-Min.-Oberflächenströmung<br><a href="${SOURCES.copernicus}" target="_blank">Datensatz</a></p><p><b>Fischereiregeln & Schutzgebiete</b><br>Länsstyrelsen Gotland / Havs- och vattenmyndigheten / Svenska Fiskeregler<br><a href="${RULES}" target="_blank">Regeln</a> · <a href="${HVMFS}" target="_blank">HVMFS 2023:11</a> · <a href="${SOURCES.fiskeregler}" target="_blank">Kartendienst</a></p></div>`)}
function backup(){let blob=new Blob([JSON.stringify({version:'6.1.2',customSpots,home,favs:[...favs]},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gotland-sea-trout-v6.1.2-backup.json';a.click()}
function enableWatch(){if(!navigator.geolocation){alert('Standort nicht verfügbar.');return}if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null;status('GPS-Warnung beendet.');return}if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();watchId=navigator.geolocation.watchPosition(pos=>{let p=[pos.coords.latitude,pos.coords.longitude];if(!window.meMarker)window.meMarker=L.circleMarker(p,{radius:8,color:'#1565c0',fillOpacity:.8}).addTo(map);else window.meMarker.setLatLng(p);if(pointInProtection(p[0],p[1])&&Date.now()-lastProtectionNotice>10*60*1000){lastProtectionNotice=Date.now();let msg='Achtung: Deine GPS-Position liegt in einer dargestellten amtlichen Schutzfläche. Bitte prüfe die geltende Vorschrift.';status(msg);if('Notification'in window&&Notification.permission==='granted')new Notification('Gotland Sea Trout',{body:msg})}},()=>status('Standort konnte nicht gelesen werden.'),{enableHighAccuracy:true,maximumAge:10000});closeSheet();status('GPS-Warnung aktiv, solange die App geöffnet ist.')}
$('#baseBtn').onclick=()=>{cancelModes(false);satelliteOn=!satelliteOn;if(satelliteOn){map.removeLayer(street);satellite.addTo(map);$('#baseBtn').textContent='▦'}else{map.removeLayer(satellite);street.addTo(map);$('#baseBtn').textContent='▱'}};
$('#locateBtn').onclick=()=>{cancelModes(false);map.locate({setView:true,maxZoom:15})};map.on('locationfound',e=>{if(!window.meMarker)window.meMarker=L.circleMarker(e.latlng,{radius:8,color:'#1565c0',fillOpacity:.85}).addTo(map);else window.meMarker.setLatLng(e.latlng)});
$('#layersBtn').onclick=layerSheet;$('#todayBtn').onclick=today;$('#moreBtn').onclick=moreSheet;
$('#addSpotBtn').onclick=()=>{if(addMode){cancelModes();return}cancelModes(false);addMode=true;$('#addSpotBtn').classList.add('active');$('#addSpotBtn').textContent='✕ Abbrechen';status('Tippe auf der Karte auf deinen neuen Spot.')};
$('#homeBtn').onclick=()=>{if(homeMode){cancelModes();return}cancelModes(false);homeMode=true;$('#homeBtn').classList.add('active');$('#homeBtn').textContent='✕ Abbrechen';status('Tippe auf die Position des Ferienhauses.')};
initTimeline();renderLegends();
let currentViewportTimer=null;map.on('moveend zoomend',()=>{if(!active.current)return;clearTimeout(currentViewportTimer);currentViewportTimer=setTimeout(()=>loadVectors('current'),350)});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
