const RULES_URL='https://www.lansstyrelsen.se/gotland/djur/fiske/recreational-fishing.html';
const spots=[
['Lickershamn',57.8272,18.5173,5,280,'Kalk, Stein, Rinnen, Tang','Klassischer Bereich','Lickershamnsån'],['Sigsarve Strand',57.868,18.538,4,285,'Klint, Kies, Stein, Tang','Suchbereich',''],['Häftingsklint',57.888,18.555,4,285,'Klint, Stein, Kanten','Suchbereich',''],['Hallshuk',57.9254,18.7459,5,310,'Kies, Tang, Kalkkante','Klassischer Bereich',''],['Kappelshamn West',57.856,18.755,4,275,'Bucht, Stein, Mischgrund','Klassischer Großraum',''],['Kappelshamn Ost / Bläse',57.842,18.827,4,55,'Kalk, Stein, flache Kanten','Suchbereich',''],['Fårösund West',57.864,19.035,3,255,'Strömungsbereich, Stein/Sand','Suchbereich',''],['Fårö West / Lauter',57.969,19.098,4,285,'Kalk, Raukar, Riffkanten','Suchbereich',''],['Fårö Nord / Ekeviken',58.01,19.25,3,15,'Bucht, Sand/Stein','Suchbereich',''],['Slite Außenküste',57.707,18.84,3,70,'Inseln, Stein, Rinnen','Suchbereich',''],['Åminne / Gothem',57.574,18.805,3,85,'Sand, Stein, Flachwasser','Suchbereich','Vikeån/Gothemån'],['Katthammarsvik',57.433,18.858,4,95,'Stein, Buchten, Kanten','Suchbereich',''],['Herrvik / Östergarn',57.421,18.927,5,100,'Riffe, Tangbänder, Rinnen','Klassischer Bereich',''],['Sandviken / Östergarn',57.405,18.914,4,105,'Sand-Riff-Mischgrund','Suchbereich',''],['Ljugarn / Folhammar',57.334,18.72,5,105,'Kalkriff, Raukar, Tang','Klassischer Bereich',''],['Närsholmen',57.222,18.704,4,120,'Flache Landzunge, Rinnen','Suchbereich','Närsån'],['Grötlingbo',57.103,18.397,3,155,'Flache Kalk-/Steinküste','Suchbereich',''],['Holmhällar',56.982,18.284,4,145,'Raukar, Stein, Buchten','Suchbereich',''],['Hoburgen',56.92,18.11,4,205,'Klippen, Kalkkanten','Suchbereich',''],['Burgsvik West',57.03,18.09,3,265,'Bucht, Sand/Stein','Suchbereich',''],['Djupvik / Ekstakusten',57.289,18.13,4,270,'Offene Stein-/Riffküste','Suchbereich',''],['Klintehamn Süd',57.364,18.12,3,270,'Riffstruktur, Mischgrund','Suchbereich',''],['Västergarn',57.44,18.10,3,275,'Bucht, Sand/Stein','Suchbereich','Västergarnsån'],['Gnisvärd / Tofta',57.506,18.08,4,280,'Flach, Sand/Stein','Suchbereich',''],['Själsö / Brissund',57.70,18.30,3,285,'Kalk, Stein, Kanten','Suchbereich','Själsöån / Lummelundaån']
].map((x,i)=>({id:i+1,name:x[0],lat:x[1],lon:x[2],rating:x[3],facing:x[4],structure:x[5],kind:x[6],protected:x[7]}));
const favs=new Set(JSON.parse(localStorage.getItem('gst-favs')||'[]'));
let currentFilter='all',selectedSpot=null,parkingLayer=L.layerGroup(),forecastCache=new Map();
const map=L.map('map',{zoomControl:true}).setView([57.47,18.55],9);
const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'});
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri'});
street.addTo(map);L.control.layers({'Karte':street,'Satellit':satellite},null,{position:'topright'}).addTo(map);parkingLayer.addTo(map);
const markers=new Map(), circles=new Map();
function compass(d){if(d==null)return'–';return ['N','NO','O','SO','S','SW','W','NW'][Math.round(d/45)%8]}
function angleDiff(a,b){let d=Math.abs(a-b)%360;return Math.min(d,360-d)}
function exposureText(s,windDir){if(windDir==null)return '–';const d=angleDiff(s.facing,windDir);return d<=35?'auflandig':d<=80?'schräg auflandig':d<=120?'seitlich':'ablandig'}
function score(w,m,s){
  let n=34+s.rating*5;
  if(w?.wind_speed_10m!=null){const v=w.wind_speed_10m;if(v>=10&&v<=26)n+=13;else if(v>=5&&v<10)n+=7;else if(v<4)n-=6;else if(v>40)n-=34;else if(v>32)n-=18;
    if(w.wind_direction_10m!=null){const d=angleDiff(s.facing,w.wind_direction_10m);if(d<=35)n+=12;else if(d<=75)n+=8;else if(d<=110)n+=2;else if(d>=145)n-=12;else n-=4;}}
  if(m?.wave_height!=null){const h=m.wave_height;if(h>=.25&&h<=.85)n+=13;else if(h>.85&&h<=1.25)n+=6;else if(h>1.8)n-=30;else if(h<.1)n-=5;}
  if(m?.wave_direction!=null){const d=angleDiff(s.facing,m.wave_direction);if(d<=70)n+=5;else if(d>=145)n-=4;}
  if(m?.sea_surface_temperature!=null){const t=m.sea_surface_temperature;if(t>=4&&t<=12)n+=10;else if(t>12&&t<=15)n+=5;else if(t>18)n-=9;}
  return Math.max(0,Math.min(100,Math.round(n)));
}
function cls(sc){return sc>=72?'good':sc<45?'bad':'warn'}
async function apiJson(url){const r=await fetch(url);if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function live(spot,forecast=false){
 const key=spot.id+':'+forecast;if(forecastCache.has(key)&&Date.now()-forecastCache.get(key).ts<15*60*1000)return forecastCache.get(key).data;
 const hourly=forecast?'&hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m&forecast_hours=48':'';
 const mhourly=forecast?'&hourly=wave_height,wave_direction,sea_surface_temperature,ocean_current_velocity,ocean_current_direction,sea_level_height_msl&forecast_hours=48':'';
 const weather=`https://api.open-meteo.com/v1/forecast?latitude=${spot.lat}&longitude=${spot.lon}&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m&wind_speed_unit=kmh&timezone=auto${hourly}`;
 const marine=`https://marine-api.open-meteo.com/v1/marine?latitude=${spot.lat}&longitude=${spot.lon}&current=wave_height,wave_direction,sea_surface_temperature,ocean_current_velocity,ocean_current_direction,sea_level_height_msl&velocity_unit=kmh&timezone=auto&cell_selection=sea${mhourly}`;
 const [wr,mr]=await Promise.allSettled([apiJson(weather),apiJson(marine)]);const data={weather:wr.status==='fulfilled'?wr.value:null,marine:mr.status==='fulfilled'?mr.value:null};forecastCache.set(key,{ts:Date.now(),data});return data;
}
function liveHtml(w,m,s){const sc=score(w,m,s);return `<div class='scoreLine'><b class='scorePill ${cls(sc)}'>${sc}/100</b><span><b>${exposureText(s,w?.wind_direction_10m)}</b> · Küste ${compass(s.facing)}</span></div><div>Wind: ${w?.wind_speed_10m??'–'} km/h ${compass(w?.wind_direction_10m)} · Böen ${w?.wind_gusts_10m??'–'}</div><div>Welle: ${m?.wave_height??'–'} m ${compass(m?.wave_direction)} · Wasser ${m?.sea_surface_temperature??'–'} °C</div><div>Strömung: ${m?.ocean_current_velocity??'–'} km/h → ${compass(m?.ocean_current_direction)} · MSL ${m?.sea_level_height_msl??'–'} m</div><small>Modellbasierte Planungshilfe; keine Navigationsdaten.</small>`}
function hourlyRows(res,s){const wh=res.weather?.hourly,mh=res.marine?.hourly;if(!wh?.time&&!mh?.time)return[];const times=wh?.time||mh.time, rows=[];for(let i=0;i<Math.min(times.length,48);i++){const w={wind_speed_10m:wh?.wind_speed_10m?.[i],wind_direction_10m:wh?.wind_direction_10m?.[i],wind_gusts_10m:wh?.wind_gusts_10m?.[i]};const m={wave_height:mh?.wave_height?.[i],wave_direction:mh?.wave_direction?.[i],sea_surface_temperature:mh?.sea_surface_temperature?.[i],ocean_current_velocity:mh?.ocean_current_velocity?.[i],ocean_current_direction:mh?.ocean_current_direction?.[i],sea_level_height_msl:mh?.sea_level_height_msl?.[i]};rows.push({time:times[i],w,m,sc:score(w,m,s)});}return rows;}
function bestWindowsHtml(rows){if(!rows.length)return'';const candidates=rows.map((r,i)=>({...r,i})).filter(r=>{const h=new Date(r.time).getHours();return h>=5&&h<=21}).sort((a,b)=>b.sc-a.sc);const chosen=[];for(const r of candidates){if(chosen.every(c=>Math.abs(c.i-r.i)>=3)){chosen.push(r);if(chosen.length===4)break;}}return `<div class='bestWindows'><b>Beste Zeitfenster (48 h)</b>${chosen.map(r=>`<div><span>${new Date(r.time).toLocaleString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit'})} Uhr</span><b class='${cls(r.sc)}'>${r.sc}/100</b></div>`).join('')}</div>`}
function forecastHtml(res,s){const rows=hourlyRows(res,s);if(!rows.length)return `<div class='errorNote'>48-h-Prognose derzeit nicht verfügbar.</div>`;let html=bestWindowsHtml(rows)+`<div class='forecastRow forecastHead'><span>Zeit</span><span>Wind</span><span>Welle</span><span>Score</span></div>`;for(let i=0;i<rows.length;i+=3){const r=rows[i],t=new Date(r.time);html+=`<div class='forecastRow'><span>${t.toLocaleString('de-DE',{weekday:'short',hour:'2-digit'})}</span><span>${r.w.wind_speed_10m??'–'} ${compass(r.w.wind_direction_10m)}</span><span>${r.m.wave_height??'–'} m</span><span class='${cls(r.sc)}'><b>${r.sc}</b></span></div>`}return `<div class='forecast'>${html}</div>`}
async function openSpot(s){selectedSpot=s;map.setView([s.lat,s.lon],13);const marker=markers.get(s.id);marker.openPopup();setTimeout(async()=>{const el=marker.getPopup()?.getElement();if(!el)return;const box=el.querySelector('.live');box.innerHTML='Lade Live-Daten & 48 h…';try{const res=await live(s,true);box.innerHTML=liveHtml(res.weather?.current,res.marine?.current,s)+forecastHtml(res,s)}catch(e){box.innerHTML='Live-Daten derzeit nicht verfügbar.'}},80)}
function popup(s){const wrap=document.createElement('div');wrap.className='popup';wrap.innerHTML=`<h3>${s.name}</h3><div>${'★'.repeat(s.rating)}${'☆'.repeat(5-s.rating)}</div><p>${s.kind}<br>Struktur: ${s.structure}<br>Küste offen nach: <b>${compass(s.facing)}</b></p>${s.protected?`<div class='official'>⚠ Nähe/Region eines Schutzgewässers: <b>${s.protected}</b>. In der Schutzzeit offizielle Karte prüfen.</div>`:''}<div class='live'>Live-Daten werden geladen.</div><button class='favBtn'>${favs.has(s.id)?'★':'☆'} Favorit</button><button class='navBtn'>Navigation</button>`;wrap.querySelector('.favBtn').onclick=e=>{favs.has(s.id)?favs.delete(s.id):favs.add(s.id);localStorage.setItem('gst-favs',JSON.stringify([...favs]));e.currentTarget.textContent=`${favs.has(s.id)?'★':'☆'} Favorit`;renderList()};wrap.querySelector('.navBtn').onclick=()=>window.open(`https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lon}`,'_blank');return wrap}
spots.forEach(s=>{const c=L.circle([s.lat,s.lon],{radius:650,weight:1,opacity:.55,fillOpacity:.04,className:'searchCircle'}).addTo(map).bindTooltip(`${s.name}: Suchradius ~650 m, keine Rechtsgrenze`);circles.set(s.id,c);const m=L.marker([s.lat,s.lon]).addTo(map).bindPopup(()=>popup(s));markers.set(s.id,m);m.on('popupopen',()=>setTimeout(()=>openSpot(s),50))});
function renderList(){const box=document.querySelector('#spotList');box.innerHTML='';spots.filter(s=>currentFilter==='all'||favs.has(s.id)).forEach(s=>{const c=document.createElement('div');c.className='spotCard';c.innerHTML=`<h3>${favs.has(s.id)?'★ ':''}${s.id}. ${s.name}</h3><p>${'★'.repeat(s.rating)} · ${s.kind}</p><span class='badge'>Küste ${compass(s.facing)}</span><span class='badge'>${s.structure}</span>${s.protected?`<span class='badge'>⚠ ${s.protected}</span>`:''}`;c.onclick=()=>openSpot(s);box.appendChild(c)})}renderList();
async function buildRanking(){const panel=document.querySelector('#ranking');panel.classList.remove('hidden');panel.innerHTML='<h3>Beste Spots aktuell</h3><p>Lade Küstenbedingungen…</p>';const results=[];let idx=0;const workers=Array.from({length:5},async()=>{while(idx<spots.length){const s=spots[idx++];try{const r=await live(s,false);results.push({s,sc:score(r.weather?.current,r.marine?.current,s),w:r.weather?.current,m:r.marine?.current})}catch{results.push({s,sc:-1})}}});await Promise.all(workers);results.sort((a,b)=>b.sc-a.sc);panel.innerHTML='<h3>🏆 Beste 5 aktuell</h3><div class="errorNote">Score berücksichtigt jetzt Küstenausrichtung, Wind, Welle und Wassertemperatur. Schutzgebiete haben immer Vorrang.</div>';results.slice(0,5).forEach((r,i)=>{const row=document.createElement('div');row.className='rankRow';row.innerHTML=`<b>${i+1}</b><span><b>${r.s.name}</b><br>${r.w?.wind_speed_10m??'–'} km/h ${compass(r.w?.wind_direction_10m)} · ${exposureText(r.s,r.w?.wind_direction_10m)} · Welle ${r.m?.wave_height??'–'} m</span><button class='rankScore ${cls(r.sc)}'>${r.sc}</button>`;row.onclick=()=>openSpot(r.s);panel.appendChild(row)});document.querySelector('#status').textContent='Ranking aktualisiert: '+new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
async function buildPlanner(){const panel=document.querySelector('#ranking');panel.classList.remove('hidden');panel.innerHTML='<h3>48-h Küstenplaner</h3><p>Lade Prognosen für alle 25 Bereiche. Das kann bei langsamer Verbindung etwas dauern.</p><div class="progress"><i id="progressBar"></i></div>';const all=[];let idx=0,done=0;const workers=Array.from({length:4},async()=>{while(idx<spots.length){const s=spots[idx++];try{const r=await live(s,true);const rows=hourlyRows(r,s);all.push({s,rows})}catch{all.push({s,rows:[]})}done++;const bar=document.querySelector('#progressBar');if(bar)bar.style.width=(done/spots.length*100)+'%';}});await Promise.all(workers);
 const slots=[];for(let h=0;h<48;h+=3){const candidates=[];for(const x of all){const r=x.rows[h];if(r)candidates.push({s:x.s,...r})}candidates.sort((a,b)=>b.sc-a.sc);if(candidates[0])slots.push(candidates[0]);}
 panel.innerHTML='<h3>🗓 48-h Küstenplaner</h3><div class="errorNote">Je 3 Stunden wird der aktuell bestbewertete Spot angezeigt. Modellwerte, keine Fanggarantie.</div><div class="plannerGrid"></div>';const grid=panel.querySelector('.plannerGrid');slots.forEach(r=>{const e=document.createElement('button');e.className='plannerCell';e.innerHTML=`<span>${new Date(r.time).toLocaleString('de-DE',{weekday:'short',hour:'2-digit'})}</span><b>${r.s.name}</b><em class='${cls(r.sc)}'>${r.sc}/100</em>`;e.onclick=()=>openSpot(r.s);grid.appendChild(e)});document.querySelector('#status').textContent='48-h Planer aktualisiert.'}
async function loadParking(){parkingLayer.clearLayers();if(!selectedSpot){document.querySelector('#status').textContent='Bitte zuerst einen Spot auswählen.';return}document.querySelector('#status').textContent='Suche Parkplätze in OpenStreetMap…';const q=`[out:json][timeout:20];(node[amenity=parking](around:3000,${selectedSpot.lat},${selectedSpot.lon});way[amenity=parking](around:3000,${selectedSpot.lat},${selectedSpot.lon});relation[amenity=parking](around:3000,${selectedSpot.lat},${selectedSpot.lon}););out center tags;`;try{const data=await apiJson('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q));let n=0;data.elements.forEach(e=>{const lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;if(lat&&lon){n++;const name=e.tags?.name||'OSM-Parkplatz';L.marker([lat,lon],{title:name}).addTo(parkingLayer).bindPopup(`<b>🅿 ${name}</b><br><small>OpenStreetMap-Datensatz; Zufahrt/Regeln vor Ort prüfen.</small>`)}});document.querySelector('#status').textContent=`${n} OSM-Parkplätze im Umkreis von 3 km gefunden.`}catch{document.querySelector('#status').textContent='Parkplatzsuche derzeit nicht verfügbar.'}}
function seasonGuard(){const m=new Date().getMonth()+1;if(m>=9||m===1){const el=document.querySelector('#seasonWarning');el.classList.remove('hidden');document.body.classList.add('hasWarning');el.innerHTML=`⚠ Schutzzeit auf Gotland: 1. September–31. Januar gelten in 25 Schutzgebieten vollständige Angelverbote. Vor jedem Spot die offizielle Karte prüfen.`}}
seasonGuard();
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderList()});
document.querySelector('#refreshBtn').onclick=()=>{forecastCache.clear();selectedSpot?openSpot(selectedSpot):document.querySelector('#status').textContent='Cache geleert. Bitte Spot auswählen.'};
document.querySelector('#locateBtn').onclick=()=>map.locate({setView:true,maxZoom:13});document.querySelector('#rankingBtn').onclick=buildRanking;document.querySelector('#plannerBtn').onclick=buildPlanner;document.querySelector('#parkingBtn').onclick=loadParking;document.querySelector('#rulesBtn').onclick=()=>window.open(RULES_URL,'_blank');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');

// ===== v4: own spots, diary, daily dashboard, local backup =====
const CUSTOM_KEY='gst-custom-spots-v4';
let customSpots=JSON.parse(localStorage.getItem(CUSTOM_KEY)||'[]');
let addSpotMode=false, customLayer=L.layerGroup().addTo(map), protectedLayer=L.layerGroup().addTo(map);

function saveCustom(){localStorage.setItem(CUSTOM_KEY,JSON.stringify(customSpots));}
function modal(html){document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modal').classList.remove('hidden')}
function closeModal(){document.querySelector('#modal').classList.add('hidden');document.querySelector('#modalBody').innerHTML=''}
document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};

function renderProtectionHints(){protectedLayer.clearLayers();spots.filter(s=>s.protected).forEach(s=>{
  L.circle([s.lat,s.lon],{radius:1300,className:'protectedHalo',interactive:false}).addTo(protectedLayer);
});}
renderProtectionHints();

function renderCustom(){customLayer.clearLayers();customSpots.forEach(s=>{
 const m=L.marker([s.lat,s.lon],{title:s.name}).addTo(customLayer);
 m.on('add',()=>{const el=m.getElement();if(el)el.classList.add('customMarker')});
 m.bindPopup(`<div class='popup'><h3>📌 ${s.name}</h3><p>Eigener Spot<br>${s.note||'Keine Notiz'}</p><button onclick="window.gstDiaryAt('${s.id}')">📓 Fang eintragen</button> <button onclick="window.gstDeleteCustom('${s.id}')">Löschen</button></div>`);
});}
renderCustom();
window.gstDeleteCustom=id=>{if(!confirm('Eigenen Spot wirklich löschen?'))return;customSpots=customSpots.filter(x=>x.id!==id);saveCustom();renderCustom();renderList()};

const oldRenderList=renderList;
renderList=function(){oldRenderList();const list=document.querySelector('#spotList');if(currentFilter==='fav')return;customSpots.forEach(s=>{const c=document.createElement('div');c.className='spotCard customCard';c.innerHTML=`<h3>📌 ${s.name}</h3><p>Eigener Spot · ${s.lat.toFixed(5)}, ${s.lon.toFixed(5)}</p><span class='badge'>persönlich</span>`;c.onclick=()=>map.setView([s.lat,s.lon],14);list.appendChild(c)})};renderList();

document.querySelector('#addSpotBtn').onclick=()=>{addSpotMode=!addSpotMode;document.querySelector('#addSpotBtn').classList.toggle('active',addSpotMode);document.querySelector('#status').textContent=addSpotMode?'Tippe jetzt auf die gewünschte Stelle in der Karte.':'Eigener-Spot-Modus beendet.'};
map.on('click',e=>{if(!addSpotMode)return;addSpotMode=false;document.querySelector('#addSpotBtn').classList.remove('active');modal(`<h2>Eigenen Spot speichern</h2><div class='mapHint'>Position: ${e.latlng.lat.toFixed(5)}, ${e.latlng.lng.toFixed(5)}</div><form id='customForm' class='formGrid'><label class='span2'>Name<input name='name' required placeholder='z. B. Kleine Bucht bei ...'></label><label class='span2'>Notiz<textarea name='note' placeholder='Zugang, Boden, Waten, Köder ...'></textarea></label><button class='primaryBtn span2'>Spot speichern</button></form>`);document.querySelector('#customForm').onsubmit=ev=>{ev.preventDefault();const fd=new FormData(ev.target);customSpots.push({id:'c'+Date.now(),name:fd.get('name').trim(),note:fd.get('note').trim(),lat:e.latlng.lat,lon:e.latlng.lng});saveCustom();renderCustom();renderList();closeModal();document.querySelector('#status').textContent='Eigener Spot gespeichert.'}});

function diaryDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('gst-diary-v4',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('entries'))db.createObjectStore('entries',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function diaryAll(){const db=await diaryDb();return new Promise((res,rej)=>{const tx=db.transaction('entries','readonly');const r=tx.objectStore('entries').getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>new Date(b.date)-new Date(a.date)));r.onerror=()=>rej(r.error)})}
async function diaryPut(x){const db=await diaryDb();return new Promise((res,rej)=>{const tx=db.transaction('entries','readwrite');tx.objectStore('entries').put(x);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function diaryDelete(id){const db=await diaryDb();return new Promise((res,rej)=>{const tx=db.transaction('entries','readwrite');tx.objectStore('entries').delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function blobToDataURL(blob){return new Promise(r=>{if(!blob){r(null);return}const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(blob)})}
function dataURLtoBlob(data){if(!data)return null;const [head,b64]=data.split(',');const mime=head.match(/:(.*?);/)[1],bin=atob(b64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:mime})}
async function openDiaryForm(spotId=''){const allNames=[...spots.map(s=>({id:'s'+s.id,name:s.name})),...customSpots.map(s=>({id:s.id,name:s.name}))];modal(`<h2>Fang eintragen</h2><form id='diaryForm' class='formGrid'><label>Datum/Zeit<input name='date' type='datetime-local' required value='${new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}'></label><label>Spot<select name='spot'><option value=''>Freie Angabe</option>${allNames.map(x=>`<option value='${x.id}' ${x.id===spotId?'selected':''}>${x.name}</option>`).join('')}</select></label><label>Länge cm<input name='length' type='number' min='0' step='0.5'></label><label>Gewicht kg<input name='weight' type='number' min='0' step='0.05'></label><label>Köder / Fliege<input name='lure'></label><label>Wassertemperatur °C<input name='water' type='number' step='0.1'></label><label class='span2'>Notizen<textarea name='note' placeholder='Wind, Welle, Grund, Bisszeit, zurückgesetzt ...'></textarea></label><label class='span2'>Foto<input name='photo' type='file' accept='image/*'></label><button class='primaryBtn span2'>Eintrag speichern</button></form>`);document.querySelector('#diaryForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target), file=f.get('photo');await diaryPut({id:'d'+Date.now(),date:f.get('date'),spot:f.get('spot'),length:f.get('length'),weight:f.get('weight'),lure:f.get('lure'),water:f.get('water'),note:f.get('note'),photo:file&&file.size?file:null});closeModal();document.querySelector('#status').textContent='Fangeintrag lokal gespeichert.'}}
window.gstDiaryAt=openDiaryForm;
async function showDiary(){const rows=await diaryAll();const nameFor=id=>{if(!id)return'Freie Angabe';if(id[0]==='s'){const s=spots.find(x=>x.id===+id.slice(1));return s?.name||id}return customSpots.find(x=>x.id===id)?.name||id};modal(`<h2>📓 Fangtagebuch</h2><p class='mapHint'>Alle Einträge und Fotos bleiben lokal auf diesem Gerät. ${rows.length} Einträge.</p><button id='newDiary' class='primaryBtn'>＋ Neuer Eintrag</button><div id='diaryRows'></div>`);document.querySelector('#newDiary').onclick=()=>openDiaryForm('');const box=document.querySelector('#diaryRows');if(!rows.length){box.innerHTML='<p>Noch keine Einträge.</p>';return}for(const r of rows){const div=document.createElement('div');div.className='diaryEntry';div.innerHTML=`<b>${new Date(r.date).toLocaleString('de-DE')}</b> · ${nameFor(r.spot)}<br><small>${r.length?`${r.length} cm`:''} ${r.weight?`· ${r.weight} kg`:''} ${r.lure?`· ${r.lure}`:''}</small><p>${r.note||''}</p>${r.photo?`<img src='${URL.createObjectURL(r.photo)}' alt='Fangfoto'>`:''}<button class='dangerBtn'>Löschen</button>`;div.querySelector('button').onclick=async()=>{if(confirm('Eintrag löschen?')){await diaryDelete(r.id);showDiary()}};box.appendChild(div)}}
document.querySelector('#diaryBtn').onclick=showDiary;

async function todayDashboard(){const panel=document.querySelector('#ranking');panel.classList.remove('hidden');panel.innerHTML='<h3>☀ Heute auf Gotland</h3><p>Lade Tagesfenster…</p><div class="progress"><i id="progressBar"></i></div>';const all=[];let idx=0,done=0;const workers=Array.from({length:4},async()=>{while(idx<spots.length){const s=spots[idx++];try{const r=await live(s,true);all.push({s,rows:hourlyRows(r,s)})}catch{all.push({s,rows:[]})}done++;const b=document.querySelector('#progressBar');if(b)b.style.width=(done/spots.length*100)+'%'}});await Promise.all(workers);const periods=[['Früh',5,9],['Mittag',10,15],['Abend',16,21]];const best=[];for(const [label,a,b] of periods){let cand=[];for(const x of all){for(const r of x.rows){const d=new Date(r.time);if(d.toDateString()===new Date().toDateString()&&d.getHours()>=a&&d.getHours()<=b)cand.push({label,s:x.s,...r})}}cand.sort((x,y)=>y.sc-x.sc);if(cand[0])best.push(cand[0])}panel.innerHTML='<h3>☀ Heute auf Gotland</h3><div class="errorNote">Beste modellierte Fenster nach Wind, Küstenausrichtung, Welle und Wassertemperatur. Schutzregeln haben Vorrang.</div><div class="dashboardGrid"></div>';const grid=panel.querySelector('.dashboardGrid');best.forEach(r=>{const d=document.createElement('div');d.className='dashCard';d.innerHTML=`<span>${r.label} · ${new Date(r.time).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</span><b>${r.s.name}</b><em class='${cls(r.sc)}'>${r.sc}/100</em><small>${r.w.wind_speed_10m??'–'} km/h ${compass(r.w.wind_direction_10m)} · ${r.m.wave_height??'–'} m</small>`;d.onclick=()=>openSpot(r.s);grid.appendChild(d)})}
document.querySelector('#todayBtn').onclick=todayDashboard;

async function exportBackup(){const entries=await diaryAll();const prepared=[];for(const e of entries)prepared.push({...e,photo:await blobToDataURL(e.photo)});const payload={version:4,exported:new Date().toISOString(),customSpots,diary:prepared};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gotland-sea-trout-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}
async function importBackup(file){const data=JSON.parse(await file.text());if(!data||data.version!==4)throw new Error('Unbekanntes Backupformat');if(Array.isArray(data.customSpots)){customSpots=data.customSpots;saveCustom();renderCustom();renderList()}if(Array.isArray(data.diary)){for(const x of data.diary){x.photo=dataURLtoBlob(x.photo);await diaryPut(x)}}document.querySelector('#status').textContent='Backup importiert.'}
document.querySelector('#exportBtn').onclick=()=>modal(`<h2>Backup & Wiederherstellung</h2><p>Exportiert eigene Spots und Fangtagebuch inklusive Fotos in eine JSON-Datei.</p><div class='backupRow'><button id='doExport' class='primaryBtn'>⇩ Backup herunterladen</button><button id='doImport' class='primaryBtn'>⇧ Backup importieren</button></div>`);document.addEventListener('click',e=>{if(e.target?.id==='doExport')exportBackup();if(e.target?.id==='doImport')document.querySelector('#importFile').click()});document.querySelector('#importFile').onchange=async e=>{try{await importBackup(e.target.files[0]);closeModal()}catch(err){alert('Import fehlgeschlagen: '+err.message)}e.target.value=''};
