const RULES='https://www.lansstyrelsen.se/gotland/djur/fiske/recreational-fishing.html';
const HVMFS='https://www.havochvatten.se/download/18.66b74fcf189fa80353fab44/1708708185345/HVMFS%202023-11-ev.pdf';
const SOURCES={osm:'https://www.openstreetmap.org/copyright',emodnet:'https://emodnet.ec.europa.eu/en/bathymetry',openmeteo:'https://open-meteo.com/',copernicus:'https://data.marine.copernicus.eu/product/BALTICSEA_ANALYSISFORECAST_PHY_003_006/description'};
const spots=[
['Lickershamn',57.8259,18.5161,5,280,'Kalk, Stein, Rinnen, Tang','Lickershamnsån'],['Sigsarve Strand',57.8664,18.5328,4,285,'Klint, Kies, Stein, Tang','Ihreån'],['Häftingsklint',57.8855,18.5487,4,285,'Klint, Stein, Kanten',''],['Hallshuk',57.9238,18.7442,5,310,'Kies, Tang, Kalkkante',''],['Kappelshamn West',57.8554,18.7468,4,275,'Bucht, Stein, Mischgrund','Vaste å / Kioskbäcken'],['Kappelshamn Ost / Bläse',57.8412,18.8330,4,55,'Kalk, Stein, flache Kanten',''],['Fårösund West',57.8629,19.0302,3,255,'Strömung, Stein/Sand',''],['Fårö West / Lauter',57.9680,19.0908,4,285,'Kalk, Raukar, Riffkanten',''],['Fårö Nord / Ekeviken',58.0087,19.2528,3,15,'Bucht, Sand/Stein',''],['Slite Außenküste',57.7061,18.8485,3,70,'Inseln, Stein, Rinnen',''],['Åminne / Gothem',57.5729,18.8098,3,85,'Sand, Stein, Flachwasser','Vikeån / Gothemsån'],['Katthammarsvik',57.4321,18.8626,4,95,'Stein, Buchten, Kanten',''],['Herrvik / Östergarn',57.4200,18.9330,5,100,'Riffe, Tangbänder, Rinnen',''],['Sandviken / Östergarn',57.4038,18.9204,4,105,'Sand-Riff-Mischgrund',''],['Ljugarn / Folhammar',57.3319,18.7270,5,105,'Kalkriff, Raukar, Tang','Halsegårdaån / Hugreifsån / Gartarveån / Bane å'],['Närsholmen',57.2202,18.7110,4,120,'Flache Landzunge, Rinnen','Närkån'],['Grötlingbo',57.1008,18.4045,3,155,'Flache Kalk-/Steinküste',''],['Holmhällar',56.9800,18.2904,4,145,'Raukar, Stein, Buchten',''],['Hoburgen',56.9185,18.1170,4,205,'Klippen, Kalkkanten',''],['Burgsvik West',57.0288,18.0842,3,265,'Bucht, Sand/Stein',''],
// v6.1: Djupvik auf den tatsächlich kartierten Küsten-/Hafenbereich korrigiert
['Djupvik / Ekstakusten',57.3084,18.1490,4,270,'Offene Stein-/Riffküste, Sandstrand',''],['Klintehamn Süd',57.3618,18.1150,3,270,'Riffstruktur, Mischgrund',''],['Västergarn',57.4381,18.0940,3,275,'Bucht, Sand/Stein','Västergarnsån'],['Gnisvärd / Tofta',57.5045,18.0730,4,280,'Flach, Sand/Stein',''],
// v6.1: Själsö auf Själsö hamn / reale Westküste korrigiert
['Själsö',57.6922,18.3521,3,285,'Kalk, Stein, Kanten','Själsöån / Kolenskvarnån']
].map((x,i)=>({id:i+1,name:x[0],lat:x[1],lon:x[2],rating:x[3],facing:x[4],structure:x[5],protected:x[6]}));

const map=L.map('map',{zoomControl:true}).setView([57.47,18.55],9);
const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri'});
const bathy=L.tileLayer.wms('https://ows.emodnet-bathymetry.eu/wms',{layers:'emodnet:mean_multicolour',format:'image/png',transparent:true,opacity:.62,attribution:'EMODnet Bathymetry'});
const spotLayer=L.layerGroup().addTo(map),parkingLayer=L.layerGroup(),customLayer=L.layerGroup().addTo(map),homeLayer=L.layerGroup().addTo(map),windLayer=L.layerGroup(),currentLayer=L.layerGroup(),tempLayer=L.layerGroup(),protectedLayer=L.layerGroup().addTo(map);
let satelliteOn=false,addMode=false,homeMode=false,selectedSpot=null,watchId=null,lastProtectionNotice=0,timelineIndex=0,timelineHours=[],active={wind:false,current:false,temp:false,bathy:false,parking:false,spots:true,custom:true,home:true,protected:true};
let customSpots=JSON.parse(localStorage.getItem('gst-custom-v6')||'[]');let home=JSON.parse(localStorage.getItem('gst-home-v6')||'null');
const favs=new Set(JSON.parse(localStorage.getItem('gst-favs')||'[]'));
const $=s=>document.querySelector(s);const status=t=>$('#status').textContent=t;
function compass(d){if(d==null)return'–';return ['N','NO','O','SO','S','SW','W','NW'][Math.round(d/45)%8]}
function angleDiff(a,b){let d=Math.abs(a-b)%360;return Math.min(d,360-d)}
function exposure(s,d){if(d==null)return'–';const x=angleDiff(s.facing,d);return x<=35?'auflandig':x<=80?'schräg auflandig':x<=120?'seitlich':'ablandig'}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function openSheet(html){cancelModes(false);$('#sheetBody').innerHTML=html;$('#sheet').classList.remove('hidden')}
function closeSheet(){$('#sheet').classList.add('hidden');$('#sheetBody').innerHTML=''}
$('#closeSheet').onclick=closeSheet;$('#sheet').onclick=e=>{if(e.target.id==='sheet')closeSheet()};
function googleNav(lat,lon){window.open(`https://www.google.com/maps/dir/?api=1&destination=${lat},${lon}`,'_blank')}
function score(w,m,s){let n=35+s.rating*6;if(w?.wind_speed_10m>=8&&w.wind_speed_10m<=28)n+=12;if(w?.wind_direction_10m!=null){let d=angleDiff(s.facing,w.wind_direction_10m);if(d<70)n+=12;if(d>145)n-=10}if(m?.wave_height>=.2&&m.wave_height<=1)n+=12;if(m?.sea_surface_temperature>=4&&m.sea_surface_temperature<=14)n+=10;return Math.max(0,Math.min(100,Math.round(n)))}
async function live(s,forecast=false){let h=forecast?'&hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m&forecast_hours=48':'';let mh=forecast?'&hourly=wave_height,wave_direction,sea_surface_temperature,ocean_current_velocity,ocean_current_direction&forecast_hours=48':'';let wu=`https://api.open-meteo.com/v1/forecast?latitude=${s.lat}&longitude=${s.lon}&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m&wind_speed_unit=kmh&timezone=auto${h}`;let mu=`https://marine-api.open-meteo.com/v1/marine?latitude=${s.lat}&longitude=${s.lon}&current=wave_height,wave_direction,sea_surface_temperature,ocean_current_velocity,ocean_current_direction&velocity_unit=kn&timezone=auto&cell_selection=sea${mh}`;let [w,m]=await Promise.allSettled([json(wu),json(mu)]);return{w:w.value||null,m:m.value||null}}
function seasonActive(){let m=new Date().getMonth()+1;return m>=9||m===1}
function destination(lat,lon,bearing,meters){let R=6371000,b=bearing*Math.PI/180,p1=lat*Math.PI/180,l1=lon*Math.PI/180,d=meters/R;let p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(b));let l2=l1+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return[p2*180/Math.PI,l2*180/Math.PI]}
function satCenters(s){return [destination(s.lat,s.lon,s.facing,120),destination(s.lat,s.lon,s.facing,210),destination(s.lat,s.lon,s.facing,120)];}
function spotIcon(s){return L.divIcon({className:'numberedSpot',html:`<span>${s.id}</span>`,iconSize:[30,30],iconAnchor:[15,15]})}
function customIcon(i){return L.divIcon({className:'customSpotIcon',html:`<span>E${i+1}</span>`,iconSize:[34,34],iconAnchor:[17,17]})}

async function openSpot(s,isCustom=false){selectedSpot=s;map.setView([s.lat,s.lon],14);let title=isCustom?`E${customSpots.indexOf(s)+1} · ${s.name}`:`${s.id} · ${s.name}`;openSheet(`<h2>${favs.has(s.id)?'★ ':''}${title}</h2><div class="subtle">${isCustom?(s.note||'Eigener Spot'):`${'★'.repeat(s.rating)} · ${s.structure} · Küste ${compass(s.facing)}`}</div><div id="spotLive" class="metricGrid"><div class="metric"><small>Live-Daten</small><b>lädt…</b></div></div><div class="actions">${!isCustom?`<button id="favA" class="actionBtn">${favs.has(s.id)?'★ Favorit':'☆ Favorit'}</button>`:''}<button id="parkA" class="actionBtn primary">🅿 Parkplatz</button><button id="navA" class="actionBtn">↗ Spot navigieren</button>${isCustom?'<button id="ce" class="actionBtn">✎ Bearbeiten</button><button id="cd" class="actionBtn danger">Löschen</button>':''}</div>${s.protected?`<div class="officialBox">⚠ ${seasonActive()?'Schutzzeit aktiv. ':''}Nähe eines geschützten Gewässers (${s.protected}). Maßgeblich ist die amtliche Schutzfläche. <a href="${RULES}" target="_blank">Offizielle Regeln</a></div>`:''}<h3>Satellitenansicht</h3><div class="subtle">Die Bildausschnitte sind bewusst seewärts versetzt, damit Küstenlinie und Flachwasser sichtbar bleiben.</div><div class="satGrid"><div><div id="sat1" class="satMap"></div><div class="satCap">Übersicht</div></div><div><div id="sat2" class="satMap"></div><div class="satCap">Küste</div></div><div><div id="sat3" class="satMap"></div><div class="satCap">Detail</div></div></div><div id="parkResults"></div>`);
 if(!isCustom)$('#favA').onclick=()=>{favs.has(s.id)?favs.delete(s.id):favs.add(s.id);localStorage.setItem('gst-favs',JSON.stringify([...favs]));openSpot(s);renderList()};$('#navA').onclick=()=>googleNav(s.lat,s.lon);$('#parkA').onclick=()=>loadParkingNear(s,true);
 if(isCustom){$('#ce').onclick=()=>editCustom(s);$('#cd').onclick=()=>{if(confirm('Spot löschen?')){customSpots=customSpots.filter(x=>x.id!==s.id);saveCustom();renderCustom();closeSheet()}}}
 let centers=isCustom?[destination(s.lat,s.lon,270,120),destination(s.lat,s.lon,270,200),destination(s.lat,s.lon,270,100)]:satCenters(s);[13,15,17].forEach((z,i)=>setTimeout(()=>{let mm=L.map('sat'+(i+1),{zoomControl:false,attributionControl:false,scrollWheelZoom:false}).setView(centers[i],z);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19}).addTo(mm);L.circleMarker([s.lat,s.lon],{radius:4,weight:1,fillOpacity:.8}).addTo(mm)},50));
 try{let r=await live(s,true),w=r.w?.current,m=r.m?.current,sc=score(w,m,{rating:s.rating||3,facing:s.facing||270});$('#spotLive').innerHTML=`<div class="metric"><small>Score</small><b>${sc}/100</b></div><div class="metric"><small>Wind</small><b>${w?.wind_speed_10m??'–'} km/h</b><small>${compass(w?.wind_direction_10m)} · ${exposure({facing:s.facing||270},w?.wind_direction_10m)}</small></div><div class="metric"><small>Welle</small><b>${m?.wave_height??'–'} m</b><small>${compass(m?.wave_direction)}</small></div><div class="metric"><small>Wasser</small><b>${m?.sea_surface_temperature??'–'} °C</b><small>Strömung ${m?.ocean_current_velocity??'–'} kn ${compass(m?.ocean_current_direction)}</small></div>`}catch{$('#spotLive').innerHTML='<div class="warnBox">Live-Daten derzeit nicht verfügbar.</div>'}}

function renderSpots(){spotLayer.clearLayers();spots.forEach(s=>L.marker([s.lat,s.lon],{title:`${s.id} ${s.name}`,icon:spotIcon(s)}).on('click',()=>openSpot(s)).addTo(spotLayer))}renderSpots();
function renderList(){let b=$('#spotList');b.innerHTML='';spots.forEach(s=>{let d=document.createElement('div');d.className='spotCard';d.innerHTML=`<h3><span class="listNo">${s.id}</span>${favs.has(s.id)?'★ ':''}${s.name}</h3><p>${s.structure}</p><span class="badge">Küste ${compass(s.facing)}</span>`;d.onclick=()=>openSpot(s);b.appendChild(d)})}renderList();
function renderCustom(){customLayer.clearLayers();customSpots.forEach((s,i)=>L.marker([s.lat,s.lon],{title:s.name,icon:customIcon(i)}).bindTooltip(`E${i+1} · ${s.name}`).on('click',()=>openSpot(s,true)).addTo(customLayer))}renderCustom();
function saveCustom(){localStorage.setItem('gst-custom-v6',JSON.stringify(customSpots))}
function editCustom(s){openSheet(`<h2>Eigenen Spot</h2><form id="cf" class="formGrid"><label class="span2">Name<input name="name" required value="${s?.name||''}"></label><label class="span2">Notiz<textarea name="note">${s?.note||''}</textarea></label><label>Bewertung<select name="rating"><option>1</option><option>2</option><option selected>3</option><option>4</option><option>5</option></select></label><label>Küste zeigt nach<select name="facing"><option value="0">N</option><option value="90">O</option><option value="180">S</option><option value="270" selected>W</option></select></label><button class="actionBtn primary span2">Speichern & Detail öffnen</button></form>`);$('#cf').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);s.name=f.get('name');s.note=f.get('note');s.rating=+f.get('rating');s.facing=+f.get('facing');saveCustom();renderCustom();openSpot(s,true)}}
function cancelModes(msg=true){addMode=false;homeMode=false;$('#addSpotBtn')?.classList.remove('active');$('#homeBtn')?.classList.remove('active');if($('#addSpotBtn'))$('#addSpotBtn').textContent='＋ Spot';if($('#homeBtn'))$('#homeBtn').textContent='⌂ Ferienhaus';if(msg)status('Auswahl abgebrochen.')}
map.on('click',e=>{if(addMode){cancelModes(false);let s={id:'c'+Date.now(),lat:e.latlng.lat,lon:e.latlng.lng,name:'Neuer Spot',note:'',rating:3,facing:270};customSpots.push(s);saveCustom();renderCustom();editCustom(s)}else if(homeMode){cancelModes(false);home={lat:e.latlng.lat,lon:e.latlng.lng,name:'Ferienhaus'};localStorage.setItem('gst-home-v6',JSON.stringify(home));renderHome();status('Ferienhaus gespeichert.')}});
function renderHome(){homeLayer.clearLayers();if(home)L.marker([home.lat,home.lon],{icon:L.divIcon({className:'homeIcon',html:'🏠',iconSize:[28,28]})}).bindTooltip(home.name).on('click',()=>googleNav(home.lat,home.lon)).addTo(homeLayer)}renderHome();

function hav(a,b){const R=6371000,p1=a[0]*Math.PI/180,p2=b[0]*Math.PI/180,dp=(b[0]-a[0])*Math.PI/180,dl=(b[1]-a[1])*Math.PI/180;const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function coastDistance(p,coastPts){let min=Infinity;for(const q of coastPts){let d=hav([p.lat,p.lon],q);if(d<min)min=d}return min}
async function parkingQuery(bounds){let bb=`${bounds.s},${bounds.w},${bounds.n},${bounds.e}`;let q=`[out:json][timeout:25];(node[amenity=parking](${bb});way[amenity=parking](${bb});way[natural=coastline](${bb}););out center geom 250;`;return json('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q))}
function parseParking(d){let coast=[];d.elements.filter(x=>x.tags?.natural==='coastline').forEach(w=>(w.geometry||[]).forEach(g=>coast.push([g.lat,g.lon])));return d.elements.filter(x=>x.tags?.amenity==='parking').map(x=>({lat:x.lat||x.center?.lat,lon:x.lon||x.center?.lon,name:x.tags?.name||'Parkplatz',access:x.tags?.access||''})).filter(x=>x.lat&&(!x.access||!['private','no'].includes(x.access))).map(p=>({...p,coast:coastDistance(p,coast)})).filter(p=>p.coast<=330).sort((a,b)=>a.coast-b.coast)}
async function loadParkingNear(s,showInSheet=false){status('Suche küstennahe Parkplätze…');let dlat=.04,dlon=.075;try{let d=await parkingQuery({s:s.lat-dlat,w:s.lon-dlon,n:s.lat+dlat,e:s.lon+dlon}),arr=parseParking(d).filter(p=>hav([s.lat,s.lon],[p.lat,p.lon])<4000);parkingLayer.clearLayers();arr.forEach(p=>L.marker([p.lat,p.lon],{icon:L.divIcon({className:'parkingIcon',html:'P',iconSize:[25,25]})}).bindTooltip(`${p.name} · ~${Math.round(p.coast)} m zur Küste`).on('click',()=>googleNav(p.lat,p.lon)).addTo(parkingLayer));parkingLayer.addTo(map);active.parking=true;if(showInSheet){let box=$('#parkResults');box.innerHTML='<h3>Parkplätze ≤ ca. 300 m zur Küste</h3>'+(!arr.length?'<p class="subtle">Keine passenden OSM-Parkplätze gefunden.</p>':arr.slice(0,8).map((p,i)=>`<button class="actionBtn parkLink" data-i="${i}">🅿 ${p.name} · ~${Math.round(p.coast)} m</button>`).join(''));box.querySelectorAll('.parkLink').forEach(b=>b.onclick=()=>googleNav(arr[+b.dataset.i].lat,arr[+b.dataset.i].lon))}status(`${arr.length} küstennahe Parkplätze gefunden.`)}catch{status('Parkplatzsuche derzeit nicht verfügbar.')}}
async function loadParkingViewport(){if(map.getZoom()<11){status('Für Parkplätze bitte näher an die Küste zoomen.');return}let b=map.getBounds();try{let d=await parkingQuery({s:b.getSouth(),w:b.getWest(),n:b.getNorth(),e:b.getEast()}),arr=parseParking(d);parkingLayer.clearLayers();arr.forEach(p=>L.marker([p.lat,p.lon],{icon:L.divIcon({className:'parkingIcon',html:'P',iconSize:[25,25]})}).bindTooltip(`${p.name} · ~${Math.round(p.coast)} m zur Küste`).on('click',()=>googleNav(p.lat,p.lon)).addTo(parkingLayer));parkingLayer.addTo(map);active.parking=true;status(`${arr.length} Parkplätze ≤ ca. 300 m zur Küste.`)}catch{status('Parkplätze derzeit nicht verfügbar.')}}

// Grobe reine Darstellungs-Landmaske. Sie ist KEINE Rechts-/Küstengrenze und dient nur dazu, Wetter-/Meeres-Pfeile auf Land zu unterdrücken.
const gotlandPoly=[[56.91,18.10],[56.96,18.18],[57.00,18.25],[57.06,18.31],[57.12,18.38],[57.20,18.50],[57.28,18.63],[57.35,18.75],[57.42,18.93],[57.50,18.91],[57.60,18.84],[57.70,18.88],[57.79,18.87],[57.87,18.84],[57.93,18.77],[57.94,18.67],[57.91,18.58],[57.86,18.52],[57.78,18.43],[57.70,18.35],[57.61,18.25],[57.51,18.12],[57.42,18.08],[57.31,18.12],[57.20,18.12],[57.10,18.10],[57.00,18.06]];
const faroPoly=[[57.86,19.00],[57.91,19.02],[57.98,19.06],[58.03,19.14],[58.04,19.26],[58.00,19.35],[57.94,19.32],[57.90,19.23],[57.87,19.12]];
function inPoly(lat,lon,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let yi=poly[i][0],xi=poly[i][1],yj=poly[j][0],xj=poly[j][1];let hit=((yi>lat)!=(yj>lat))&&(lon<(xj-xi)*(lat-yi)/(yj-yi)+xi);if(hit)inside=!inside}return inside}
function isLand(p){return inPoly(p.lat,p.lon,gotlandPoly)||inPoly(p.lat,p.lon,faroPoly)}
const vectorPoints=[];for(let lat=56.90;lat<=58.06;lat+=.07)for(let lon=17.98;lon<=19.40;lon+=.09){let p={lat:+lat.toFixed(3),lon:+lon.toFixed(3)};if(!isLand(p))vectorPoints.push(p)}
function currentColor(v){if(v<.25)return'#79c6d8';if(v<.5)return'#4aa9c2';if(v<1)return'#65b86d';if(v<1.5)return'#d7cf42';if(v<2)return'#ef9a38';if(v<2.5)return'#df5b3e';return'#9d1635'}
function arrowIcon(kind,dir,val,label){let size=kind==='current'?Math.max(16,Math.min(42,16+val*11)):Math.max(16,Math.min(34,16+val*.35));let color=kind==='current'?currentColor(val):'#183f82';return L.divIcon({className:'vectorIcon',html:`<div class="vectorArrow ${kind}" style="font-size:${size}px;color:${color};transform:rotate(${dir}deg)">➤</div><div class="vectorValue">${label}</div>`,iconSize:[48,48],iconAnchor:[24,24]})}
function timeParam(){return timelineHours[timelineIndex]||null}
async function loadVectors(kind){let layer=kind==='wind'?windLayer:currentLayer;layer.clearLayers();active[kind]=true;updateTimeline();status(kind==='wind'?'Lade Windfeld…':'Lade Strömungsfeld…');let pts=vectorPoints.filter((_,i)=>i%2===0);await Promise.allSettled(pts.map(async p=>{try{if(kind==='wind'){let d=await json(`https://api.open-meteo.com/v1/forecast?latitude=${p.lat}&longitude=${p.lon}&hourly=wind_speed_10m,wind_direction_10m&wind_speed_unit=kmh&forecast_hours=48&timezone=auto`),idx=Math.min(timelineIndex,(d.hourly?.time?.length||1)-1),v=d.hourly?.wind_speed_10m?.[idx],dir=d.hourly?.wind_direction_10m?.[idx];if(v!=null)L.marker([p.lat,p.lon],{icon:arrowIcon('wind',(dir+180)%360,v,Math.round(v))}).addTo(layer)}else{let d=await json(`https://marine-api.open-meteo.com/v1/marine?latitude=${p.lat}&longitude=${p.lon}&hourly=ocean_current_velocity,ocean_current_direction&velocity_unit=kn&forecast_hours=48&timezone=auto&cell_selection=sea`),idx=Math.min(timelineIndex,(d.hourly?.time?.length||1)-1),v=d.hourly?.ocean_current_velocity?.[idx],dir=d.hourly?.ocean_current_direction?.[idx];if(v!=null)L.marker([p.lat,p.lon],{icon:arrowIcon('current',dir,v,(+v).toFixed(1))}).bindTooltip(`${(+v).toFixed(2)} kn · ${compass(dir)}`).addTo(layer)}}catch{}}));layer.addTo(map);status(kind==='wind'?'Windfeld aktiv.':'Strömung: Pfeilgröße und Farbe zeigen Geschwindigkeit. Land wird maskiert.')} 
function tempColor(t){if(t<6)return'#275aa8';if(t<9)return'#2c7bb6';if(t<12)return'#73add1';if(t<15)return'#abd9e9';if(t<17)return'#fdae61';if(t<19)return'#f46d43';return'#d73027'}
async function loadTemp(){tempLayer.clearLayers();active.temp=true;updateTimeline();status('Lade Wassertemperatur…');let pts=vectorPoints.filter((_,i)=>i%4===0);await Promise.allSettled(pts.map(async p=>{try{let d=await json(`https://marine-api.open-meteo.com/v1/marine?latitude=${p.lat}&longitude=${p.lon}&hourly=sea_surface_temperature&forecast_hours=48&timezone=auto&cell_selection=sea`),idx=Math.min(timelineIndex,(d.hourly?.time?.length||1)-1),t=d.hourly?.sea_surface_temperature?.[idx];if(t!=null)L.circle([p.lat,p.lon],{radius:7000,stroke:false,fillColor:tempColor(t),fillOpacity:.32}).bindTooltip(`${t} °C`).addTo(tempLayer)}catch{}}));tempLayer.addTo(map);status('Wassertemperatur aktiv.')} 
function setLayer(key,on){active[key]=on;let layer={spots:spotLayer,custom:customLayer,home:homeLayer,protected:protectedLayer,parking:parkingLayer,bathy,wind:windLayer,current:currentLayer,temp:tempLayer}[key];if(!on){if(map.hasLayer(layer))map.removeLayer(layer)}else if(key==='wind')loadVectors('wind');else if(key==='current')loadVectors('current');else if(key==='temp')loadTemp();else if(key==='parking')loadParkingViewport();else layer.addTo(map);renderLegends();updateTimeline()}
function switchHtml(key,label){return `<div class="layerRow ${active[key]?'on':''}"><span>${label}</span><label class="switch"><input type="checkbox" data-layer="${key}" ${active[key]?'checked':''}><span class="slider"></span></label></div>`}
function layerSheet(){openSheet(`<h2>Karten-Layer</h2><div class="layerList">${switchHtml('spots','🎣 Angelspots')}${switchHtml('custom','📌 Eigene Spots')}${switchHtml('parking','🅿 Küstenparkplätze ≤ ~300 m')}${switchHtml('protected','⚠ Schutzgebiete')}${switchHtml('current','🌊 Strömung')}${switchHtml('wind','💨 Wind')}${switchHtml('temp','🌡 Wassertemperatur')}${switchHtml('bathy','〰 Wassertiefen')}${switchHtml('home','🏠 Ferienhaus')}</div><p class="depthNote">Zeitabhängige Layer nutzen gemeinsam die Zeitachse unten auf der Karte. Strömung in dieser Testversion wird noch über Open-Meteo bezogen; die Copernicus/SMHI-Anbindung ist als nächste Datenquellenstufe vorbereitet.</p>`);document.querySelectorAll('[data-layer]').forEach(x=>x.onchange=e=>{setLayer(e.target.dataset.layer,e.target.checked);e.target.closest('.layerRow').classList.toggle('on',e.target.checked)})}
function renderLegends(){let b=$('#mapLegends');let html='';if(active.current)html+=`<div class="mapLegend"><b>Strömung · kn</b><div class="grad currentGrad"></div><div class="ticks"><span>0</span><span>.5</span><span>1</span><span>1.5</span><span>2</span><span>≥2.5</span></div><small>Pfeilgröße = Geschwindigkeit</small></div>`;if(active.temp)html+=`<div class="mapLegend"><b>Wasser · °C</b><div class="grad tempGrad"></div><div class="ticks"><span>6</span><span>9</span><span>12</span><span>15</span><span>17</span><span>19+</span></div></div>`;if(active.bathy)html+=`<div class="mapLegend"><b>Wassertiefe · m</b><div class="grad depthGrad"></div><div class="ticks"><span>0</span><span>2</span><span>5</span><span>10</span><span>20</span><span>50+</span></div><small>EMODnet-Farbskala angenähert</small></div>`;b.innerHTML=html}
function initTimeline(){let now=new Date();now.setMinutes(0,0,0);timelineHours=Array.from({length:48},(_,i)=>new Date(now.getTime()+i*3600000));$('#timeRange').max=47;$('#timeRange').value=0;$('#timeRange').oninput=e=>{timelineIndex=+e.target.value;refreshTimed()};$('#playTime').onclick=playTimeline;updateTimeline()}
let playTimer=null;function playTimeline(){if(playTimer){clearInterval(playTimer);playTimer=null;$('#playTime').textContent='▶';return}$('#playTime').textContent='Ⅱ';playTimer=setInterval(()=>{timelineIndex=(timelineIndex+1)%48;$('#timeRange').value=timelineIndex;refreshTimed()},1200)}
let refreshTimer;function refreshTimed(){updateTimeline();clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{if(active.current)loadVectors('current');if(active.wind)loadVectors('wind');if(active.temp)loadTemp()},250)}
function updateTimeline(){let show=active.current||active.wind||active.temp;$('#timeline').classList.toggle('hidden',!show);let d=timelineHours[timelineIndex];if(d)$('#timeLabel').textContent=timelineIndex===0?'Jetzt':d.toLocaleString('de-DE',{weekday:'short',hour:'2-digit',minute:'2-digit'})}

// Amtlich definierte Själsö/Kolenskvarnån-Fläche aus HVMFS 2023:11, Punkte 1–4.
function dm(deg,min){return deg+min/60}
const sjalsoProtection=[[dm(57,39.893),dm(18,19.231)],[dm(57,39.893),dm(18,18.929)],[dm(57,42.100),dm(18,21.297)],[dm(57,42.099),dm(18,21.800)]];
function renderProtection(){protectedLayer.clearLayers();L.polygon(sjalsoProtection,{className:'protectedOfficial',color:'#a51f2d',weight:2,fillColor:'#e05260',fillOpacity:.30}).bindPopup(`<b>Själsöån / Kolenskvarnån</b><br>Amtliche Grenzpunkte nach HVMFS 2023:11.<br>Angelverbot 1. Sep.–31. Jan.<br><a href="${HVMFS}" target="_blank">Amtliche Vorschrift</a>`).addTo(protectedLayer)}renderProtection();

async function today(){cancelModes(false);let box=$('#ranking');box.classList.remove('hidden');box.innerHTML='<b>☀ Beste Spots jetzt</b><p>Lade Bedingungen…</p>';let out=[];for(let s of spots){try{let r=await live(s),sc=score(r.w?.current,r.m?.current,s);out.push({s,sc})}catch{}}out.sort((a,b)=>b.sc-a.sc);box.innerHTML='<b>☀ Beste Spots jetzt</b>'+out.slice(0,5).map((x,i)=>`<div class="rankRow" data-id="${x.s.id}"><b>${x.s.id}</b><span>${x.s.name}</span><b>${x.sc}/100</b></div>`).join('');box.querySelectorAll('.rankRow').forEach(r=>r.onclick=()=>openSpot(spots.find(s=>s.id==r.dataset.id)))}
function moreSheet(){openSheet(`<h2>Mehr</h2><div class="actions"><button id="rules" class="actionBtn">⚠ Regeln & Schonzeit</button><button id="parkall" class="actionBtn">🅿 Parkplätze</button><button id="backup" class="actionBtn">⇩ Backup</button><button id="gpswarn" class="actionBtn">📍 GPS-Warnung</button><button id="sources" class="actionBtn">ⓘ Quellen & Lizenzen</button></div><div class="officialBox"><b>Meerforellen-Schutzbereiche:</b> Laut Länsstyrelsen gibt es 25 Schutzbereiche an 34 Gewässern. In den Mündungsbereichen gilt 1. September–31. Januar Angelverbot. Die App verwendet keine geschätzten Kreise.</div><p class="subtle">v6.1 zeigt bereits die amtlich koordinierte Själsö/Kolenskvarnån-Fläche. Die übrigen amtlichen Flächen werden nur ergänzt, wenn ihre Geometrie ohne Schätzung aus der Vorschrift/Karte rekonstruiert werden kann.</p>`);$('#rules').onclick=()=>window.open(RULES,'_blank');$('#parkall').onclick=()=>{loadParkingViewport();closeSheet()};$('#backup').onclick=backup;$('#gpswarn').onclick=enableWatch;$('#sources').onclick=sourcesSheet}
function sourcesSheet(){openSheet(`<h2>Quellen & Lizenzen</h2><div class="sourceList"><p><b>Basiskarte / Parkplätze</b><br>© OpenStreetMap contributors · ODbL<br><a href="${SOURCES.osm}" target="_blank">Lizenz & Attribution</a></p><p><b>Satellitenbilder</b><br>Esri World Imagery · Attribution wird direkt auf der Kartenebene angezeigt.</p><p><b>Bathymetrie</b><br>EMODnet Bathymetry<br><a href="${SOURCES.emodnet}" target="_blank">Quelle</a></p><p><b>Wind / Wellen / SST / derzeitige Strömungsdarstellung</b><br>Open-Meteo / Marine Weather API<br><a href="${SOURCES.openmeteo}" target="_blank">Quelle</a></p><p><b>Geplante hochauflösendere Ostsee-Strömung</b><br>Copernicus Marine / Baltic Sea Physics (SMHI)<br><a href="${SOURCES.copernicus}" target="_blank">Datensatz</a></p><p><b>Fischereiregeln & Schutzgebiete</b><br>Länsstyrelsen Gotland / Havs- och vattenmyndigheten<br><a href="${RULES}" target="_blank">Regeln</a> · <a href="${HVMFS}" target="_blank">HVMFS 2023:11</a></p></div>`)}
function backup(){let blob=new Blob([JSON.stringify({version:'6.1',customSpots,home,favs:[...favs]},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gotland-sea-trout-v6.1-backup.json';a.click()}
function pointInProtection(lat,lon){return inPoly(lat,lon,sjalsoProtection)}
function enableWatch(){if(!navigator.geolocation){alert('Standort nicht verfügbar.');return}if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null;status('GPS-Warnung beendet.');return}if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();watchId=navigator.geolocation.watchPosition(pos=>{let p=[pos.coords.latitude,pos.coords.longitude];if(!window.meMarker)window.meMarker=L.circleMarker(p,{radius:8,color:'#1565c0',fillOpacity:.8}).addTo(map);else window.meMarker.setLatLng(p);if(pointInProtection(p[0],p[1])&&Date.now()-lastProtectionNotice>10*60*1000){lastProtectionNotice=Date.now();let msg='Achtung: Du befindest dich in der amtlich definierten Schutzfläche Själsöån/Kolenskvarnån.';status(msg);if('Notification'in window&&Notification.permission==='granted')new Notification('Gotland Sea Trout',{body:msg})}},()=>status('Standort konnte nicht gelesen werden.'),{enableHighAccuracy:true,maximumAge:10000});closeSheet();status('GPS-Warnung aktiv, solange die App geöffnet ist.')}
$('#baseBtn').onclick=()=>{cancelModes(false);satelliteOn=!satelliteOn;if(satelliteOn){map.removeLayer(street);satellite.addTo(map);$('#baseBtn').textContent='▦'}else{map.removeLayer(satellite);street.addTo(map);$('#baseBtn').textContent='▱'}};
$('#locateBtn').onclick=()=>{cancelModes(false);map.locate({setView:true,maxZoom:15})};map.on('locationfound',e=>{if(!window.meMarker)window.meMarker=L.circleMarker(e.latlng,{radius:8,color:'#1565c0',fillOpacity:.85}).addTo(map);else window.meMarker.setLatLng(e.latlng)});
$('#layersBtn').onclick=layerSheet;$('#todayBtn').onclick=today;$('#moreBtn').onclick=moreSheet;
$('#addSpotBtn').onclick=()=>{if(addMode){cancelModes();return}cancelModes(false);addMode=true;$('#addSpotBtn').classList.add('active');$('#addSpotBtn').textContent='✕ Abbrechen';status('Tippe auf der Karte auf deinen neuen Spot.')};
$('#homeBtn').onclick=()=>{if(homeMode){cancelModes();return}cancelModes(false);homeMode=true;$('#homeBtn').classList.add('active');$('#homeBtn').textContent='✕ Abbrechen';status('Tippe auf die Position des Ferienhauses.')};
initTimeline();renderLegends();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
